README.md

Adding a hint that the React codecov badge is actually only for react (since the badge is on the main README which also covers the backend).

707 - add 'React' hint for the codecov badge

---

react/package.json
react/yarn.lock

As specified in [this issue](https://trello.com/c/e370D6Nk/720-update-create-react-app-configuration-so-that-it-uses-non-deprecated-packages), we need to update the create-react-app module because the current version we use is deprecated. This opens us up to high-level security vulnerabilities.
* Ran ```yarn add --exact react-scripts@4.0.3``` as specified in the create-react-app [changelog](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md) and [documentation](https://create-react-app.dev/docs/updating-to-new-releases/)

Update create-react-app version

---

.circleci/config.yml
flask/test/endpoint_tests/test_app.py

- combination of test_box endpoint unit test and database configuration
from main.py (use read request)
- configure circleci to launch a MySQL server, and run unit / integration tests separately
@HaGuesto why do we expose the mysql docker-compose service on port 32000 instead of 3306?

Add integration test using actual MySQL database connection

---

.github/dependabot.yml

Basically followed the instructions [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) and in the sibling pages.
Are you fine with the values for the check interval?
In the beginning we'll probably see some PRs to get all dependencies up-to-date.

Configure dependabot to update pip and npm packages

---

flask/README.md
flask/boxwise_flask/models/__init__.py
flask/boxwise_flask/models/beneficiary.py
flask/boxwise_flask/models/history.py
flask/boxwise_flask/models/log.py
flask/boxwise_flask/models/settings.py
flask/boxwise_flask/models/transaction.py
flask/boxwise_flask/models/x_beneficiary_language.py
flask/test/auth_tests/conftest.py
flask/test/data/__init__.py
flask/test/data/beneficiary.py
flask/test/data/history.py
flask/test/data/log.py
flask/test/data/settings.py
flask/test/data/setup_tables.py
flask/test/data/transaction.py
flask/test/endpoint_tests/conftest.py
flask/test/model_tests/conftest.py
flask/test/model_tests/test_beneficiary.py
flask/test/model_tests/test_history.py
flask/test/model_tests/test_log.py
flask/test/model_tests/test_settings.py
flask/test/model_tests/test_transaction.py

Just wanting to get some early feedback here - I added four new peewee models using pwiz (two are covered by unit tests).
Following the 'Python Models Import for Peewee document', the following transfers are still missing
* people_tags
* tags
* x_people_languages
* history (mentioned twice in the document with ChangeHistory / DBChangeHistory as Python model)
1. Should I add those here?
2. Regarding the field naming: do we go for underscored names rather?

More tables as peewee models

---

.circleci/config.yml
docker-compose.yml
flask/README.md
flask/boxwise_flask/graph_ql/query_defs.py
flask/boxwise_flask/graph_ql/resolvers.py
flask/boxwise_flask/graph_ql/type_defs.py
flask/boxwise_flask/models/base.py
flask/boxwise_flask/models/box.py
flask/boxwise_flask/models/location.py
flask/boxwise_flask/models/qr_code.py
flask/boxwise_flask/models/size.py
flask/test/data/box.py
flask/test/endpoint_tests/conftest.py
flask/test/endpoint_tests/test_app.py
flask/test/endpoint_tests/test_bases.py
flask/test/endpoint_tests/test_box.py
flask/test/endpoint_tests/test_create_box.py
flask/test/endpoint_tests/test_qr.py
flask/test/endpoint_tests/test_simple.py
flask/test/model_tests/test_box.py

This PR shows a PoC for box resolvers. I implemented the four resolvers as requested, and learnt a lot about the resolver 'magic' that ariadne provides. It ties together nicely with peewee since the rows returned by DB queries can be directly accessed for their attributes (we should watch out for a 1-to-1 mapping between the GraphQL field names and the Peewee field names. Conversion of camelCase and snake_case happens semi-automatically. For anything else we can have custom resolvers, e.g. below for the ID field).
@aerinsol 
1. you asked me about the query design, I'm not quite decisive yet about the approach. As a BE engineer I'd probably opt for the second approach because it does not require additional handling (number of) of the arguments.
1.1 parametrized query (`GetBoxDetails`): …

Proof of concept: box resolvers

---

flask/boxwise_flask/graph_ql/resolvers.py
flask/test/endpoint_tests/test_base.py
flask/test/endpoint_tests/test_bases.py
flask/test/endpoint_tests/test_permissions.py

This PR adds a resolver that I had previously missed to implement.
On a side-note @vahidbazzaz, I also checked the boxes resolver of the location query. It's not possible to retrieve unauthorized data since the location resolver checks whether the user has access to the location's base, and only if the base can be accessed, the `boxes` will be resolved by filtering w.r.t. the location.

Add base locations resolver

---

docker-compose.yml
flask/Dockerfile
flask/README.md
flask/boxwise_flask/graph_ql/resolvers.py
flask/boxwise_flask/models/beneficiary.py
flask/boxwise_flask/models/location.py
flask/boxwise_flask/models/product.py
flask/gunicorn.conf.py
flask/scripts/load-test.js

This PR contains some modifications to enable load-testing and profiling of the app.
The goal is to find out whether the app currently already shows severe bottlenecks for data IO, network, memory, and/or CPU usage.
On my local machine I ran two different experiments using the flask/mysql Docker services. For the results I don't put absolute numbers since they'll be different/non-comparable when running the experiments with the app deployed to GAE or similar.
- Load-testing using [k6](https://k6.io/docs/)
- Profiling the app
1. Load-testing
1. The scenario is a running server running the webapp, and several clients sending **as many requests as possible**. We want to find out about the throughput (requests / sec), and the latency (i.e. request waiting time for client == processing time …

App load testing and profiling

---

back/boxtribute_server/graph_ql/enums.py
back/boxtribute_server/graph_ql/pagination.py
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/types.graphql
back/boxtribute_server/models/product_gender.py

As a preparation for future FE implementation, I had a look at the [previous](https://github.com/boxwise/boxtribute/blob/36529720613db62176bf3221613369bb0630ce8c/react/src/utils/queries.ts) query definitions, and run them in the playground. Indeed I could find two inconsistencies :)
Further comments on the queries:
- USER: parameter `id` instead of `email`
- ALL_BASES, BASE, ORG_BASES: nested field `organisation { id }` instead of `organisationId`
- BOX_BY_QR: misleading name since it fetches box by `boxLabelIdentifier`. `size` and `state` instead of `size_id` and `box_state_id`
- PRODUCTS: now a paginated query. Accepts PaginationInput argument and returns ProductPage type
@aerinsol @haguesto How does the dropapp handle the ProductGender with ID 10? It does not have any name associated …

Fix GraphQL resolvers and enums

---

back/boxtribute_server/enums.py
back/boxtribute_server/graph_ql/operations.graphql
back/boxtribute_server/graph_ql/types.graphql
back/boxtribute_server/models/crud.py
back/boxtribute_server/models/definitions/shipment.py
back/boxtribute_server/models/definitions/transfer_agreement.py
back/test/data/shipment.py
back/test/data/transfer_agreement.py
back/test/model_tests/test_crud.py

To be reviewed in combination with the database ERD and the user action list linked in the Trello ticket below.
This is a first version, feel free to comment/review if anything is of major concern. I likely change things a little bit during implementation.
- the types represent the hierarchy of the data layer: agreement -> shipment -> shipment detail
- the agreement details are available as TransferAgreement.sourceBases and .targetBases
- updateShipment can be used for three different actions
- sendShipment and completeShipment serve as trigger for Shipment state transitions
- accept/rejectTransferAgreement serve as trigger for TransferAgreement state transitions

Update GraphQL types and operations for box-transfer

---

back/boxtribute_server/enums.py
back/boxtribute_server/graph_ql/enums.py
back/boxtribute_server/graph_ql/operations.graphql
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/schema.py
back/boxtribute_server/graph_ql/types.graphql
back/boxtribute_server/models/definitions/transfer_agreement.py
back/test/data/__init__.py
back/test/data/shipment.py
back/test/data/transfer_agreement.py
back/test/data/transfer_agreement_detail.py
back/test/endpoint_tests/test_shipment.py
back/test/endpoint_tests/test_transfer_agreement.py

That worked well...setting up the queries to fetch transfer agreements and shipments via GraphQL
For filtering, the following applies:
- filtering by organisation happens implicitly by only returning agreements/shipments that the current client's organisation is involved in (as either source or target)
- agreements can be filtered by state
- shipments cannot be further filtered
Do you agree with these decisions?
Anyways we can always extend the filtering logic in the process of developing the MVP and beyond =)
https://trello.com/c/e7vZrQAP/804-implement-graphql-queries-for-box-transfer

Implement GraphQL queries for box-transfer

---

back/Dockerfile
back/README.md
back/gunicorn.conf.py
back/scripts/load-test.js
docker-compose.yml

Contributes to https://trello.com/c/yZXAchvk/810-fix-docker-app-setup-for-macs
Changed it to: 
* port is 5000 within the container and for the flask configuration 
* just the exposed port/port forwarding from container to host is 5005

810 use 5005 for host only

---

back/boxtribute_server/exceptions.py
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/models/crud.py
back/boxtribute_server/models/definitions/shipment.py
back/test/data/__init__.py
back/test/data/base.py
back/test/data/shipment.py
back/test/data/transfer_agreement.py
back/test/endpoint_tests/test_shipment.py
back/test/endpoint_tests/test_transfer_agreement.py
back/test/model_tests/test_crud.py

This PR adds the implementation for the `createShipment`, `cancelShipment`, `sendShipment` mutations, incl. appropriate validations (e.g. for shipment state).
The corresponding test cases are 3.2.1 - 3.2.14 in https://docs.google.com/spreadsheets/d/1sDhSsaVwNxAhGn1VYACDPVepZpvlwTkgy9nmeTaRy2Q/edit#gid=1709672082 (last sheet) with the exception of the cases dealing with non-existent resources (will be handled in generic way).
I have two questions regarding these test cases:
- *3.2.10* Is it correct that only a member of the organisation that originally created the shipment can cancel that shipment?
- *3.2.14* For validating that the confirming user is member of the organisation that created the shipment I first need to retrieve information about the creating organisation. We don't …

GraphQL mutations for shipment flow

---

back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/types.graphql
back/boxtribute_server/models/crud.py
back/test/data/__init__.py
back/test/data/box.py
back/test/data/location.py
back/test/data/shipment.py
back/test/endpoint_tests/test_location.py
back/test/endpoint_tests/test_shipment.py
back/test/model_tests/test_crud.py

This PR implements part II of the GraphQL mutations for the box-transfer feature.
The corresponding test cases are 3.2.20 - 3.2.32.
One question (cf. test case 3.2.25): can members of both organisations update the bases of an existing shipment?
Note that in the implementation for test cases 3.2.27, .28, .31, no errors are indicated in the GraphQL response (I didn't see any way to return a partial response because only one resolver (for `updateShipment` mutation is involved. It would be possible to return a custom `ShipmentUpdateResponse` type holding successful and erroneous updates. I don't how much benefit it brings since that part of the API won't be public).

GraphQL mutations for update-shipment flow

---

back/boxtribute_server/auth.py
back/boxtribute_server/authz.py
back/boxtribute_server/graph_ql/resolvers.py
back/test/auth.py
back/test/auth_tests/test_authz.py
back/test/data/beneficiary.py
back/test/data/product.py
back/test/endpoint_tests/test_app.py
back/test/endpoint_tests/test_beneficiary.py
back/test/endpoint_tests/test_permissions.py

- Make test data and its usage more consistent
- Integrate new Auth0 permissions format
Some ideas to decrease the JWT payload size for @vahidbazzaz
- only send `:write` or `:edit` permission (I can derive the corresponding `:read` permission)
- do we need `box_state:read`, `category:read`, `gender:read`, `language:read`, `sizegroup:read`? The underlying data is not user-specific. Even if the permissions were part of the payload, I would not enforce them in the BE for simplicity.
What do you think?

Integrate new permission format

---

back/boxtribute_server/authz.py
back/boxtribute_server/box_transfer/agreement.py
back/boxtribute_server/box_transfer/shipment.py
back/boxtribute_server/graph_ql/operations.graphql
back/boxtribute_server/graph_ql/resolvers.py
back/test/auth.py
back/test/auth_tests/test_authz.py
back/test/endpoint_tests/test_app.py
back/test/endpoint_tests/test_beneficiary.py
back/test/endpoint_tests/test_permissions.py
back/test/endpoint_tests/test_shipment.py
back/test/endpoint_tests/test_transfer_agreement.py
back/test/utils.py

This PR brings these updates:
- Enforce basic DB-based permissions for transfer agreement and shipment (`shipment:read`/`:write`, same for `transfer_agreement`)
- previously, unauthorized actions for modifying agreements or shipments were consider bad user input (i.e. validation failed) whereas actually they are examples of forbidden actions. The respective implementations are moved to the resolvers level for clear distinction
- two more edge test cases to verify authorized user for creating shipment/canceling agreement
@vahidbazzaz Once the discussion about the corresponding action name, and which users to grant the action is finished, you can extend the Auth0 scripts such that users with the respective permissions in their JWT can actually access shipments/agreements.

Enforce DB-based permissions for box-transfer

---

back/README.md
back/boxtribute_server/box_transfer/shipment.py
back/boxtribute_server/exceptions.py
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/models/crud.py
back/boxtribute_server/routes.py
back/test/endpoint_tests/test_app.py
back/test/endpoint_tests/test_beneficiary.py
back/test/endpoint_tests/test_qr.py
back/test/endpoint_tests/test_shipment.py
back/test/endpoint_tests/test_transfer_agreement.py
back/test/model_tests/test_crud.py
back/test/utils.py
example.envrc

This PR brings
- some improvements for database error handling and how they are reported to the client (hide away potential raw SQL queries)
- covering two more test cases with `updateShipment` mutation
- fix for updating beneficiary gender
- improved function signatures for `crud.create/update_beneficiary`
- disabling GraphQL introspection in non-development mode
Let me know if you have any questions :)

GraphQL improvements

---

.circleci/config.yml

The 'circleci' namespace is deprecated as per Dec 31st, 2021 (see
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034)

Update CircleCI Docker images

---

back/boxtribute_server/graph_ql/filtering.py
back/boxtribute_server/graph_ql/operations.graphql
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/scalars.py
back/boxtribute_server/graph_ql/types.graphql
back/boxtribute_server/models/crud.py
back/boxtribute_server/models/definitions/beneficiary.py
back/boxtribute_server/models/definitions/transaction.py
back/boxtribute_server/models/fields.py
back/test/data/__init__.py
back/test/data/beneficiary.py
back/test/data/box.py
back/test/data/transaction.py
back/test/endpoint_tests/test_app.py
back/test/endpoint_tests/test_beneficiary.py
back/test/endpoint_tests/test_box.py
back/test/endpoint_tests/test_permissions.py
back/test/integration_tests/test_operations.py

This PR brings an extension of the GraphQL API:
- queries for beneficiaries and boxes can now be filtered (see the new filter types in `types.graphql` @aerinsol)
- the `Beneficiary` type is extended by fields `age`, `active` (indicate whether soft-deleted or not), and `transactions`
Let me know about any remarks.

GraphQL filters and fixes

---

.gitignore
back/README.md
back/boxtribute_server/graph_ql/inputs.graphql
back/boxtribute_server/graph_ql/mutations.graphql
back/boxtribute_server/graph_ql/queries.graphql
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/types.graphql
back/test/data/beneficiary.py
back/test/endpoint_tests/test_beneficiary.py
docs/graphql-api/Dockerfile
docs/graphql-api/README.md
docs/graphql-api/full-api-config.yml
docs/graphql-api/metadata.json
docs/graphql-api/query-api-config.yml
docs/graphql-api/run

Here comes the documentation of our GraphQL documentation.
After some research, I decided to use [SpectaQL](https://github.com/anvilco/spectaql) for generation (I consider it an active, well-documented project. Indeed it was very easy to set up). The generated GraphQL documentation (excluding mutations) is attached to the linked Trello card. Please extract it and have a look at `index.html` in your web browser. I really like the interactivity of the documentation framework.
As a preparation I split the schema definitions into several files:
- "external" API consumers access queries and relevant types (no mutations)
- our front-end consumes the full schema (queries, types, mutations, inputs)
I have a local repository for building the documentation. What do you think about putting the …

Create GraphQL documentation

---

.circleci/config.yml

Previously, the deploy-job failed when merging to master ([example](https://app.circleci.com/pipelines/github/boxwise/boxtribute/850/workflows/02e09815-0d3b-4122-bdd2-842f50eaf215/jobs/3606)). This was due to an outdated cache path for the Python virtualenv. I updated the path and also made caching in the test-flask job more efficient.
I tested the successful deploy by triggering a deploy from this branch (hardcoding the `filters.branches` field).

Repair gcloud deploy

---

.circleci/config.yml
.gitignore
back/README.md
back/boxtribute_server/auth.py
back/boxtribute_server/routes.py
back/scripts/load-test.js
back/test/auth.py
back/test/integration_tests/test_jwt.py
docker-compose.yml
example.env
fetch_token

- added dedicated API and application in Auth0
- introduce QUERY_API_* env variables in CircleCI (distinguish from
those for the webapp backend)
This avoids returning an ID token on the `/token` endpoint. Instead only an access token is returned, and acc. to convention only such a token should be used to convey user authorization information (cf. https://auth0.com/blog/id-token-access-token-what-is-the-difference/)
Successfully tested with `POST /token` and api.boxtribute.org.

Fix Auth0 configuration

---

LICENSE.md
README.md
docs/graphql-api/full-api-config.yml
docs/graphql-api/query-api-config.yml

License is now rendered as markdown: https://github.com/boxwise/boxtribute/blob/docs/833-update-license-and-tos/LICENSE.md

Docs: update license formatting and ToS

---

.circleci/config.yml
docs/graphql-api/query-api-config.yml

The URL for the respective query API is updated (both in the right and left column, and in the auth/authz section).
Please see https://api-staging.boxtribute.org/docs and https://api-demo.boxtribute.org/docs

Adjust query API URL in docs depending on context

---

react/.prettierignore
react/src/App.tsx
react/src/GlobalPreferencesProvider.tsx
react/src/components/HeaderMenu.tsx
react/src/generated/graphql.tsx
react/src/index.tsx
react/src/utils/test-utils.tsx
react/src/views/Home.tsx
react/src/views/automatic-base-switcher/AutomaticBaseSwitcher.tsx
react/src/views/boxes/Boxes.tsx
react/src/views/locations/Locations.test.tsx
react/src/views/locations/Locations.tsx

Closes https://trello.com/c/byffqWJL/865-enable-switching-between-bases-for-new-frontend
Also it adds
* a automatic base switcher: for root urls like `http://domain.xyz/`, the first base of the list of all bases where the user has access to will be selected (OR, in the future, we can implement a 'go to latest used base from previous session' - see next point)
* a global preference context (also things like the most recently used base can be stored there, if the same user comes back to the app in the future, it can be used to automatically go to this base; we can leverage the localStorage for that)

Base switcher

---

back/boxtribute_server/auth.py
back/boxtribute_server/authz.py
back/boxtribute_server/graph_ql/resolvers.py
back/test/data/__init__.py
back/test/data/product.py
back/test/data/shipment.py
back/test/endpoint_tests/test_permissions.py

Regardless of the value of the `organisation_id` claim in the JWT, set the internal `CurrentUser.organisation_id` to None for god users, and update involved filtering logic accordingly.

Handle authz for god users

---

.circleci/config.yml
README.md
back/Dockerfile
back/README.md
back/app.yaml
back/requirements-dev.txt
back/requirements.txt
back/setup.py

Dear developers,
this PR is relevant to you if you actively develop in the boxtribute Python code base. With this PR, Python 3.10 is the minimum version that the software supports (older versions might still work), please install it on your system and perform the back-end installation steps. If you only user the docker-compose services, you don't need to take action.
Content of the PR:
- Update Python docker images
- Bump Python dependencies
Opening some PRs in dependencies' repos:
- https://github.com/timster/peewee-moves/pull/17
- https://github.com/benoitc/gunicorn/pull/2805
- https://github.com/corydolphin/flask-cors/pull/314

Upgrade to Python 3.10

---

back/boxtribute_server/box_transfer/agreement.py
back/boxtribute_server/graph_ql/inputs.graphql
back/boxtribute_server/models/definitions/shipment.py
back/boxtribute_server/models/definitions/shipment_detail.py
back/boxtribute_server/models/definitions/transfer_agreement.py
back/boxtribute_server/models/definitions/transfer_agreement_detail.py
back/test/endpoint_tests/test_transfer_agreement.py
docker-compose.yml

In preparation for the migration scripts coming in dropapp for creating transfer-agreement related tables in the MySQL databases.
FYI @spaudanjo @flisowna when creating a transfer agreement, an optional comment can be passed now.

Make peewee generate underscore table names

---

.gitignore
back/.gitignore
back/boxtribute_server/graph_ql/pagination.py
react/.gitignore
react/src/views/Boxes/BoxesView.test.tsx
react/src/views/Boxes/BoxesView.tsx

Loading the Boxes view in the FE was reportedly slow. I first looked at the GraphQL query issued by the FE, and then dug into the SQL queries run by peewee in the BE. I could find a redundant `select * from stock` query as a side-effect from peewee objects (still trying to understand the background).
@spaudanjo @flisowna Can you check the performance in the FE on your end?

Improve performance of boxes-for-base query

---

back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/models/definitions/product.py
react/src/types/generated/graphql.ts
react/src/views/Boxes/BoxesView.tsx

I had another look at the performance of the BoxesForBase query.
Using a profiler I found three bottlenecks:
- Avoid unnecessary SELECT for product gender ID (this is a peewee caveat, fixed)
- Remove redundant query for box place (was fixed in #292 but re-introduced when renaming happened, fixed)
- resolving `boxes { elements { product { } } }` results in a lot of separated SELECT queries for products (same for size, presumably). I hacked a basic loader (storing a single call of `Product.select()` in a dictionary) which brought down runtime of the product resolver from 1.4s to 0.14s
As a conclusion from the third bottleneck, and because the other slow queries have similar complexity, I think we defs have to look into data loaders.
FYI @aerinsol

Improve complex GraphQL queries

---

back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/loaders.py
back/boxtribute_server/models/definitions/product.py
back/boxtribute_server/routes.py
back/requirements.txt
back/scripts/load-test.js
back/test/endpoint_tests/test_permissions.py
back/test/integration_tests/test_operations.py

After some research I managed to integrate dataloaders provided by the [aiodataloader](https://github.com/syrusakbary/aiodataloader) package.
Under the hood this results in batching of DB queries, and hence a significant speed-up of request processing time.
Using a local testing setup I obtained a decrease of processing time from 4.5s down to 0.7s for the GraphQL request behind the [BoxesView](https://github.com/boxwise/boxtribute/blob/master/react/src/views/Boxes/BoxesView.tsx#L8).
I verified that the database queries are batched using peewee's logger, and also verified data integrity by comparing the result of the query between master and this branch.
As discussed, it is important to deploy this on the staging server to test how the BE behaves with concurrent requests.

Introduce dataloaders

---

back/boxtribute_server/auth.py
back/boxtribute_server/authz.py
back/test/auth_tests/test_authz.py

As a follow-up to #374.
- assign authorized=False and empty base IDs to User object by default
- handle edge case: resource-permission given but no bases assigned

Make authorize() function even more robust

---

.circleci/config.yml

- Introduce separate checkout job
- Don't run build-/test-flask jobs for deploy workflows

Fix deploy triggered by tag

---

.circleci/config.yml
react/src/index.tsx

Depending on the CircleCI context, the value is
staging/demo/production. See also
https://docs.sentry.io/platforms/javascript/guides/react/configuration/options/#environment

Set SENTRY_ENVIRONMENT variable when building front-end

---

back/boxtribute_server/models/crud.py
back/boxtribute_server/models/utils.py
back/test/endpoint_tests/test_box.py
back/test/model_tests/test_crud.py

This PR adds two utility decorators that shall be applied on the data-operational level to any function that creates or updated a resource.
Please see the function docstrings for information. The implemented functionality is identical to the dropapp functionality (in the formhandler module). See also [this section](https://github.com/boxwise/dropapp/blob/master/include/stock_edit.php#L30)
The decorators are applied to the `create_box` and `update_box` functions since they are the only relevant ones for the upcoming deploy. Two unit tests had to be converted into endpoint tests because the new decorators require access to an actual Flask app context (for fetching client information).
For local testing try the following:
1. Start docker-compose services `docker-compose up webapp db`
1. Open …

Add entries in history table when running box mutation

---

back/boxtribute_server/models/utils.py

- Use built-in request attribute to fetch user IP address
- Test-deploy on this branch

Use client IP for history table pt. II

---

back/boxtribute_server/graph_ql/inputs.graphql
back/boxtribute_server/models/crud.py
back/test/endpoint_tests/test_box.py

Please see the attached trello card for context. It's now possible to write a mutation like
```
mutation { createBox(creationInput: {
...
tagIds: [1, 3]
}) { 
tags { id } 
} }
```
with the response `{"tags": [1, 3]}`

Extend createBox mutation to accept tag IDs

---

back/boxtribute_server/models/utils.py
back/test/endpoint_tests/test_box.py
docs/graphql-api/query-api-config.yml

As agreed on [Slack](https://boxwise.slack.com/archives/CB1UYDGLU/p1664879251812689).
Please see the commit message.

Don't store client IP when logging to history table

---

.circleci/config.yml
back/app-api.yaml
back/boxtribute_server/logging.py
back/boxtribute_server/routes.py
back/requirements.txt

Please see the attached trello cards for all findings. In summary: Google Cloud Logging should be cheap, fast, and convenient :)
You might want to verify the functionality by opening the [Log Explorer](https://console.cloud.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22api-staging%22;cursorTimestamp=2022-10-20T19:18:45.741484728Z?project=dropapp-242214) and filtering for the `api-requests` log.
Further changes:
- when using GraphQL playground, the `Server cannot be reached` message has disappeared, and query auto-completion works. Schema and docs can be viewed in tabs on the right edge. This is possible through enabled GraphQL introspection (meaning users can pull metadata of the schema, like underlying GraphQL object types)
- the API is …

First test of logging in Google Cloud

---

.circleci/config.yml
back/boxtribute_server/logging.py
back/requirements-deploy.txt
back/requirements.txt
react/Dockerfile

Reason:
- it's not used in local development installations anyways, and caused
trouble to install it on Macs (grcpio package).
- during deploy, the google-cloud-logging package must be explicitly
added to requirements.txt (cf.
https://cloud.google.com/appengine/docs/standard/python3/runtime#dependencies)
Follow-up to #442.

Use google-cloud-logging only in deployed environments

---

back/boxtribute_server/graph_ql/inputs.graphql
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/models/crud.py
back/test/endpoint_tests/test_box.py
back/test/endpoint_tests/test_permissions.py
react/src/types/generated/graphql.ts

Simple extension of `BoxUpdateInput`.

Enable passing tag IDs when updating box

---

back/boxtribute_server/models/crud.py
back/test/endpoint_tests/test_box.py

Remove all assigned tags when passing empty list for tag IDs

---

react/src/views/BoxEdit/components/BoxEdit.tsx

The PR adds a cancel button to the box edit so that you can navigate back to the box view from within the edit box.

BoxEdit: Add Cancel Button to go back to its origin

---

back/boxtribute_server/authz.py
back/boxtribute_server/exceptions.py
back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/types.graphql
back/boxtribute_server/loaders.py
back/test/auth.py
back/test/auth_tests/test_authz.py
back/test/data/__init__.py
back/test/data/packing_list_entry.py
back/test/data/shipment.py
back/test/data/transfer_agreement_detail.py
back/test/data/user.py
back/test/endpoint_tests/test_distribution_event.py
back/test/endpoint_tests/test_packing_list_entry.py
back/test/endpoint_tests/test_permissions.py
back/test/endpoint_tests/test_shipment.py
back/test/endpoint_tests/test_transfer_agreement.py
back/test/endpoint_tests/test_user.py

This is the first of a series of at least two PRs related to enforcing base-specific permissions. I'm breaking it down because after the authz logic was changed, there are quite some effects on the resolvers (mostly because base-specific permissions were (lazily) not enforced, or because the permission level was clarified, e.g. for transfer agreement to also operate on base-level). This means a couple of tests are failing but I'll fix them in subsequent PRs which will be merged here one by one. Eventually this branch can go into master.
You can read the background in the attached Trello card.
The main functional change is in cdb1bac4.

Make resource based permission being enforced for bases by default, part I

---

back/boxtribute_server/authz.py
back/test/auth_tests/test_authz.py

Pretty sure that `updateBox` is the only mutation involved in BoxView/BoxEdit, please correct me if wrong.

Change allowed mutations for beta user scope

---

back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/types.graphql
back/test/endpoint_tests/test_tag.py
react/src/types/generated/graphql.ts
react/src/views/BoxEdit/BoxEditView.tsx

The FE should have the ability to filter tags acc. to a resource type.
E.g. in the BoxEdit page the queries should be adjusted like:
```
base(id: $baseId) {
...
tags(resourceType: Box) { ... }
...
}
```
Otherwise tags that are only applicable to beneficiaries could be selected.

Add optional filtering for Base.tags by resource type

---

react/src/views/BoxEdit/BoxEditView.tsx

The PR fixes the badge still being visible after having removed the tag from the box by refetching the data after the update mutation. 
Although I tried adding the necessary fields back after the box mutation update in an effort to avoid refetching, it did not work. This is a quick fix.

Fix Tags Visible After Having Removed from Box

---

back/boxtribute_server/authz.py
back/boxtribute_server/graph_ql/resolvers.py

I still had some resources marked as base-agnostic. Now base-related permissions are enforced in the resolvers.

Permission update for mobile-distro resolvers

---

react/src/components/NotificationMessage.tsx

This PR fixes a minor bug that displays the last notification message when clicking the home button. Reproduce by doing any action that displays a message, then clicking on the home page logo, the last message appears again.
Follow up: https://github.com/boxwise/boxtribute/pull/494

Fix a Minor Bug that Displays the Last Notification Message on Home Page

---

back/boxtribute_server/graph_ql/resolvers.py
back/boxtribute_server/graph_ql/types.graphql
back/boxtribute_server/models/crud.py
back/test/auth.py
back/test/endpoint_tests/test_box.py

This PR brings an extension of the GraphQL API such that the history of a Box can be displayed in the FE.
For orientation I took the content of the history entries in Dropapp:
Dev Head of Operations on Monday 14 November 2022, 18:32
Dev Head of Operations changed the number of items from 15 to 17;
So the FE needs to know about the name of the user who committed the change, the change date, and the change message.

Box history GraphQL API

---

react/src/components/HeaderMenu/HeaderMenuDeskop.tsx
react/src/components/HeaderMenu/HeaderMenuMobile.tsx
react/src/utils/helpers.ts

Reason:
- set preference Session variable in dropapp to classic
- go to the same menu in dropapp on mobile.

edit links to dropapp mobile views

---

react/src/components/HeaderMenu/HeaderMenuMobile.tsx
react/src/views/Box/components/BoxDetails.tsx
react/src/views/BoxEdit/BoxEditView.tsx

The PR contains minor changes before the release, including removing the link from the logo and adding box state to the locations button and drop down menu in the edit box when the location associated box state is not equal to InStock.

Remove the Logo Link and Add State Label on the Location Buttons

---

react/src/views/Box/BoxView.test.tsx
react/src/views/Box/components/BoxDetails.tsx

In this PR, the buttons are disabled if the box state is lost or scrapped.

BoxView: Disabling Buttons on State Lost and Scrap

---

react/src/components/HeaderMenu/HeaderMenuMobile.tsx
react/src/utils/helpers.ts
react/src/views/Box/BoxView.test.tsx
react/src/views/Box/BoxView.tsx
react/src/views/Box/components/BoxDetails.tsx

In this PR, the box state label is changed to "Status" to be consistent with DropApp's UI and the mobile navigation UI link is fixed.

BoxView: Change State Label and Fix Mobile Navigation

---

.circleci/config.yml
back/app.yaml
react/public/heapanalytics.js

This PR integrates Heap Analytics into the front-end by adding scripts to index HTML during deployment. In response to these changes, an environment variable HEAPIO_APP_ID is created in the CircleCI to store the heap app ID.

Add heap.io on Frontend

---

back/boxtribute_server/app.py
back/boxtribute_server/authz.py
back/boxtribute_server/logging.py
back/boxtribute_server/routes.py
back/boxtribute_server/utils.py
back/test/endpoint_tests/test_app.py
docker-compose.yml

When running the back-end tests a warning "unknown option passed to
flask-cors: origin" could be seen. It turns out that the option
correctly has to be named 'origins'. But even then the server would
accept any origins for making requests.
More research revealed that the flask-cors offers several ways of
configuring the extension: using the `CORS` wrapper, and using the
`cross_origin` decorator. Since we used both, the former took
precedence, and it's default is to allow any origins, methods, and
headers (questionable defaults, however that's exactly what the docs
state).
As a solution, the `CORS` wrapper is removed, and the `cross_origin`
decorator is applied to the one route that matters, with the correct
options passed in.
FYI @aerinsol

Correctly configure CORS in back-end

---

.gitignore
.pre-commit-config.yaml
back/boxtribute_server/auth.py
back/boxtribute_server/authz.py
back/boxtribute_server/db.py
back/boxtribute_server/graph_ql/definitions.py
back/boxtribute_server/logging.py
back/boxtribute_server/utils.py
back/requirements-dev.txt
back/scripts/list_models.py
back/setup.py
docs/peewee-moves/peewee-moves_test_migration.py
fetch_token

This PR adds a scaffold for using mypy type checking in the back-end code base.
Type annotations will be added incrementally in other PRs.
For an introduction, check out
- https://mypy.readthedocs.io/en/stable/index.html
- https://mypy.readthedocs.io/en/stable/getting_started.html

Integrate mypy type checker

---

back/boxtribute_server/warehouse/box/crud.py
back/test/endpoint_tests/test_box.py

The issue was that we use ordering by change datetime to sort log
entries, and then select the first one as the newest one. However the
datetime has second precision, hence when two changes occur within one
second, it's not necessarily the newest one that comes first in the
ordering. The newest entry always has the largest ID, so sorting by ID
is used now.
@aerinsol I'll merge this such that you can test on staging again.

Sort history entries by ID instead of change date

---

back/boxtribute_server/authz.py

With this, mobile-distro mutations are enabled for users with beta-scope 99, and the mobile-distro pages become usable again.
I'll change selected users' metadata in the staging-tenant. For all other users, and any users in demo or prod, it will be impossible to execute mobile-distro mutations (should they find the hidden pages).

Add beta-access for mobile-distro mutations

---

back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
back/boxtribute_server/business_logic/box_transfer/shipment/mutations.py
back/boxtribute_server/enums.py
back/boxtribute_server/graph_ql/inputs.graphql
back/boxtribute_server/graph_ql/mutations.graphql
back/boxtribute_server/graph_ql/types.graphql
back/test/endpoint_tests/test_app.py
back/test/endpoint_tests/test_permissions.py
back/test/endpoint_tests/test_shipment.py
back/test/integration_tests/test_operations.py
react/src/types/generated/graphql.ts

Please see commits for details.
We probably need additional fields `updated_by`, `updated_on` in the `Shipment` model but I'm still clarifying with Roanna (code-wise it would be a minor change).

Extension of GraphQL API for shipment reception

---

docs/adr/adr_database-history.md

Proposal: go for history/shadow tables.
Read the ADR as rendered markdown [here](https://github.com/boxwise/boxtribute/blob/00f78b9cb3ffe065d22546cc10ca1e9e6b34b251/docs/adr/adr_database-history.md).
This ADR supersedes the previous [Google doc draft](https://docs.google.com/document/d/1eqcS7iYN0oIorl9JcvNm2eoY4_ogUFyLh-wQLD53SOQ/edit#).

First version of ADR for database history

---

back/boxtribute_server/models/definitions/box.py

They don't exist anymore in the underlying MySQL database, hence
queries like Box.select() fail like
Unknown column 't1.ordered' in field list

Remove deleted Box model fields

---

back/boxtribute_server/business_logic/warehouse/box/crud.py

Since the last prod deploy, the MySQL error message for when a used QR
code is added to a box is along 
Duplicate entry '153659' for key 'qr_id_unique'
but the error detection was looking for an exact match
Duplicate entry '153659' for key 'stock.qr_id_unique'
and, not finding a match, would leave this error unhandled.
A couple of occurrences have been reported by Sentry recently.
The error detection is now made less strict since we only have to
distinguish between an assignment of a duplicated QR code, a duplicated
box label identifier, or another unknown error.
This fix is important because the detection of a used QR code would
trigger an unknown error without telling the user what went wrong
(hence also the uncaught exceptions in Sentry). Now they're correctly
notified again about the …

Make error detection for re-used QR code less strict

---

back/boxtribute_server/graph_ql/loaders.py

The newest DB seeds contains tag/tag relation data. We found that a
query like `boxes { elements { tags { id } } }` performs very slow.
Introspecting peewee logs shows that thousands of individual
Tag.select() queries are performed.
The culprit is missing to additional select Tags when selecting tag relations
(which then is joined with tags). After fixing, all Tag objects are fetched in
one go instead of having peewee issue a select every time a tag object
is actually accessed.
This brings down execution time from 3.5s to about 0.7s for a query like
`shipment(id: 1) { details { boxes { tags { id } } } }`, and only
queries the TagsRelation table once.
Also only select TagsRelation that are correspond to boxes requested by
the user when batch-loading tags.

Fix slow box-query loading time if tags present

---

back/boxtribute_server/app.py

Cf. https://docs.sentry.io/platforms/python/profiling/
The env variable `SENTRY_TRACES_SAMPLE_RATE` is set for 1 in the
CircleCI staging context. Profiling will not be effective in demo nor
production environments.

Add Sentry profiling for Python BE

---

react/src/views/Box/BoxView.test.tsx
react/src/views/Box/BoxView.tsx
react/src/views/Box/components/BoxCard.tsx
react/src/views/Box/components/BoxDetails.tsx
react/src/views/Box/components/BoxMoveLocation.tsx
react/src/views/Box/components/BoxTabs.tsx

The PR disables editing and moving actions when a box is added to a shipment.

BoxView: Disable Edits and Moves While in Shipment Transit

---

react/src/views/Box/BoxView.test.tsx
react/src/views/Box/BoxView.tsx

- fix boxview tests - add cache
- add support for partial response to boxview

BoxView: Fix Tests and Update GraphQL Error Policy for BoxView Query

---

react/src/views/Box/BoxView.tsx
react/src/views/Box/components/AssignBoxToShipment.tsx
react/src/views/Box/components/BoxCard.tsx

- use the new InTransit to prevent change in the box
- prevent changing state to lost / scrap
- prevent adding the box on lost location to shipment
- prevent removing box from shipment while box state is InTransit

BoxView: Prevent State Changes or Assignments to Shipments When a Box in the Legacy Lost Location

---

back/README.md
back/boxtribute_server/business_logic/box_transfer/shipment/fields.py
back/boxtribute_server/business_logic/warehouse/box/fields.py
back/boxtribute_server/business_logic/warehouse/box/queries.py
back/boxtribute_server/graph_ql/loaders.py
back/test/auth.py
back/test/data/box.py
back/test/data/shipment_detail.py
back/test/endpoint_tests/test_app.py
back/test/endpoint_tests/test_box.py
back/test/endpoint_tests/test_classic_location.py
back/test/endpoint_tests/test_permissions.py
back/test/endpoint_tests/test_shipment.py

New behavior: If I access an InTransit or Receiving box, and I'm member of either source or target base of the corresponding shipment, 
- no authz error is thrown, and
- `Box.product` and `Box.location` return null if the box is still registered in the opposite base. I have to use `ShipmentDetail.source/targetProduct/Location` instead

Enable accessing InTransit/Receiving boxes for members of target base

---

back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
back/boxtribute_server/models/utils.py
back/test/endpoint_tests/test_shipment.py

Working on [the exploration for box movement data](https://github.com/orgs/boxwise/projects/2/views/1?pane=issue&itemId=34127114) it appeared that we have to track box movements in the context of shipments.
Now changes in box product, size, number of items, location, and state at the time of reconciliation are tracked.

update history table during shipment

---

back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
back/test/data/history.py
back/test/endpoint_tests/test_box.py
back/test/endpoint_tests/test_shipment.py

- Create list when querying shipment details instead of appending
- Update history test data
- New function for bulk updating box state during shipments and tracking the change

Update history table during shipment (box state)

---

back/boxtribute_server/business_logic/box_transfer/agreement/crud.py
back/boxtribute_server/exceptions.py
back/test/data/transfer_agreement.py
back/test/data/transfer_agreement_detail.py
back/test/endpoint_tests/test_transfer_agreement.py
back/test/integration_tests/test_operations.py

When creating an agreement, now it is first checked whether an identical accepted agreement exists, i.e. same set of organisations and same (sub)set of bases involved, and overlapping validity periods. If so, the GraphQL response contains an error with `BAD_USER_INPUT` code.

prevent creating identical agreements

---

back/boxtribute_server/business_logic/statistics/crud.py
back/boxtribute_server/business_logic/statistics/queries.py
back/boxtribute_server/exceptions.py
back/boxtribute_server/graph_ql/definitions/public_api.graphql
back/boxtribute_server/graph_ql/schema.py
back/test/data/__init__.py
back/test/data/history.py
back/test/data/product_category.py
back/test/endpoint_tests/test_box.py
back/test/endpoint_tests/test_shipment.py
back/test/endpoint_tests/test_statistics.py

This brings the new public GraphQL query `createdBoxes`.
The interface has been defined in #898.
Please verify that you can run a query like
```graphql
query { createdBoxes { facts { boxesCount } dimensions { product { id } category { id } } } }
```
without errors. In the response `facts` is expected to contain several elements; `dimensions` returns sensible data, too.
Note that the implementation is not precise with regards to possible changes in box product or item count that might have happened since creation.

GraphQL query for createdBoxes

---

back/boxtribute_server/business_logic/box_transfer/agreement/crud.py
back/boxtribute_server/business_logic/statistics/crud.py
back/boxtribute_server/graph_ql/definitions/public_api.graphql
back/boxtribute_server/models/utils.py
back/setup.cfg
back/test/endpoint_tests/test_statistics.py

See comment in #888 for the updated data format.
The FE can now filter for a combination of tag IDs in the result. A dimensions table is provided such that human-readable tag names can be used.

[1st viz] Add beneficiary tag IDs to demographics query

---

react/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.test.tsx
react/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.tsx
react/src/views/Transfers/CreateTransferAgreement/components/CreateTransferAgreement.tsx

This PR drop direction radio buttons from CreateAgreement, and set Bidirectional as default type, also update tests. (It drops the overall FE test coverage because I removed the transfer type input test cases)

CreateTransferAgreement: Drop the Transfer Type Radio Buttons

---

react/src/views/Box/BoxView.test.tsx
react/src/views/Box/components/BoxTabs.tsx

- remove the transfer tab as a temporary workaround
- update test case 4.6.1.3 and add new test case 4.6.1.3b

BoxView: Hide Trasnfer Tab If There Is No Shipment in a Preparing State Available

---

react/src/views/Box/components/BoxCard.tsx
react/src/views/Box/components/HistoryEntries.tsx

In this PR, history records are made smaller, dates are compacted, and the icon and text are aligned.
Note: Merge this [PR](https://github.com/boxwise/boxtribute/pull/982) first, then this one

BoxView: Make the Text for the Most Recent History Smaller 

---

react/src/views/Box/components/BoxCard.tsx

This PR remove extra space between box identifier and box status when there are no tags assigned to a box.

BoxView: Remove Extra Padding When Hiding Tags

---

react/src/App.tsx
react/src/components/HeaderMenu/HeaderMenu.tsx
react/src/components/HeaderMenu/HeaderMenuContainer.tsx
react/src/components/HeaderMenu/HeaderMenuDesktop.tsx
react/src/components/HeaderMenu/HeaderMenuMobile.tsx
react/src/hooks/hooks.ts
react/src/hooks/useAuthorization.ts
react/src/types/generated/graphql.ts
react/src/utils/helpers.ts
react/yarn.lock

I wrote a simple Authorization hook for routes and some initial new rendering for menues. I also fixed the redirect to dropapp in dev environments to make testing easier.
I updated dev_coordinator, dev_headofops of both organisations in staging and dev tennent in auth0 to have the "beta_user" flag with value 2.
- see the menues and be able to access /transfer/agreements route if you are a dev_coordinator
- not see the menues and not be able to access /transfer/agreements route if you are a dev_volunteer

Show menues and create protected routes based on beta flag

---

back/boxtribute_server/business_logic/statistics/crud.py
back/boxtribute_server/graph_ql/definitions/public_api.graphql
back/test/endpoint_tests/test_statistics.py
react/codegen.yml
react/src/types/generated/graphql.ts
statviz/src/types/generated/graphql.ts

As per suggestion in #969.
@maikneubert: tag color information is useful to colorize the tag label in a UI filter component. Product gender can be useful to concatenate more meaningful, distinct product names, see [this comment](https://github.com/boxwise/boxtribute/pull/969#discussion_r1301710013).

[B] add tag name & product gender to dimensions

---

back/boxtribute_server/auth.py
back/boxtribute_server/business_logic/box_transfer/agreement/crud.py
back/boxtribute_server/graph_ql/definitions/protected/inputs.graphql
back/boxtribute_server/graph_ql/scalars.py
back/requirements-dev.txt
back/requirements.txt
back/test/auth.py
back/test/endpoint_tests/test_distribution_event_tracking_group.py
back/test/endpoint_tests/test_transfer_agreement.py
back/test/unit_tests/test_authz.py
docs/adr/adr_authorization-specification.md
react/src/types/generated/graphql.ts
react/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.tsx

Timezone info is needed for the validity times input when creating an agreement. This PR pulls the info from the user JWT (put there by Auth0), and also drops a Python package dependency.

use timezone from user jwt

---

react/src/views/Transfers/ShipmentView/components/ShipmentTabs.tsx

The PR fixes the problem with the number of missing boxes not displaying at the group level.

ShipmentView: Fixed the Issue with the Number of Missing Boxes Not Being Displayed at Group Level

---

react/src/views/Transfers/ShipmentView/components/ShipmentReceivingCard.tsx

The PR changes "Remaining" to "Received" so that the number of boxes increases as they are received rather than decreasing.

ReconciliationView: Change "Remaining" to "Received"

---

react/src/views/Box/components/HistoryEntries.tsx

This PR changes the history message from "box state" to "box status" in order to comply with user-facing terminology.

BoxView: History Message Should Use "box status" Instead of "box state"

---

react/src/components/BoxReconciliationOverlay/components/BoxReconciliationAccordion.tsx

The PR fixes reconciliation view accordion to open/focus on when it is first rendered.

ReconciliationView: Open Accordion Upon First Render

---

react/src/components/BoxReconciliationOverlay/BoxReconciliationOverlay.test.tsx
react/src/components/BoxReconciliationOverlay/BoxReconciliationOverlay.tsx

The PR corrects the labels and styles of the reconciliation buttons and updates the AYS buttons labels in the test case 4.7. Also add a space after the period of the first sentence.

ReconciliationView: Change the Label and Style of the AYS Buttons 

---

back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
react/src/views/Transfers/ShipmentView/components/ShipmentReceivingCard.tsx

Can be tested by reconciling a box via the GraphQL playground.

Set ShipmentDetail.received_by/on immediately after box reconciliation

---

react/src/components/QrReader/components/QrReader.tsx

In this PR, the minus and plus buttons are removed from the QR reader overlay.

QrOverlay: remove minus and plus buttons

---

react/src/views/Transfers/ShipmentView/components/ShipmentTabs.tsx

- fix sorting order on completed shipment
- using lostOn instead of box state to count total lost boxes

ShipmentView: Sort for Completed Shipments Should Show Products Without Missing Boxes First

---

back/boxtribute_server/business_logic/statistics/crud.py
back/boxtribute_server/business_logic/statistics/queries.py
back/boxtribute_server/enums.py
back/boxtribute_server/graph_ql/definitions/public_api.graphql
back/boxtribute_server/graph_ql/enums.py
back/boxtribute_server/graph_ql/schema.py
back/test/endpoint_tests/test_statistics.py
statviz/src/types/generated/graphql.ts

This PR brings the GraphQL interface for data about moved boxes.
It can be used to generate a Sankey diagram of the number of boxes donated from a base into "donation" locations, filterable by movement day and product category.

[4th viz] Implement GraphQL interface for movedBoxes

---

back/boxtribute_server/routes.py
back/test/endpoint_tests/test_simple.py

Can be invoked in demo/prod but any POST requests (and hence inspection of the GraphQL schema, or any GraphQL requests) will be blocked in the POST handler

Add GraphQL playground for /public endpoint

---

back/boxtribute_server/authz.py
back/boxtribute_server/business_logic/core/product_category/queries.py
back/boxtribute_server/graph_ql/loaders.py
back/test/auth.py
back/test/unit_tests/test_authz.py

More precise naming matching the model name (ProductCategory)
- :heavy_check_mark: Auth0 actions updated for dev, staging, and production tenants
- :heavy_check_mark: [RBP google sheet](https://docs.google.com/spreadsheets/d/1W4YWcc59wUFUWgReumdH6DQ4zU7JcTgvf6WEbdqaGHQ/edit#gid=593366918) updated

Rename RBP to 'product_category'

---

back/boxtribute_server/business_logic/statistics/crud.py
back/boxtribute_server/enums.py
back/boxtribute_server/graph_ql/definitions/public_api.graphql
back/test/data/history.py
back/test/endpoint_tests/test_box.py
back/test/endpoint_tests/test_statistics.py
statviz/src/types/generated/graphql.ts

This PR brings two new target types ("Shipment" and "BoxState") and collect info about shipped boxes, and lost/scrap boxes, resp.) into the result of the `movedBoxes` query.
Test by connecting with prod DB and running the FE for Moved Boxes.
Target type | movedOn | targetId
--- | --- | ---
Shipment | timestamp of when the shipment was sent | name of target base
BoxState | timestamp of when the box was set to Lost/Scrap state | name of box state

[4th viz] Extend movedBoxes data with info about shipped/lost/scrap boxes

---

front/src/App.tsx
front/src/views/QrReader/components/ResolveHash.test.tsx
front/src/views/QrReader/components/ResolveHash.tsx

@pylipp and @aerinsol:
Since we disabled the [mobile part of dropapp](https://github.com/boxwise/dropapp/pull/566), there is a bit of routing that moved to v2 for the case that a user scans a QR-code with an external QR-Reader.
In this case, the external QR-Reader requests the mobile.php url from dropapp which now just forwards the qr hash to v2. The business logic if BoxView should be shown or BoxCreate or an Error lies no in v2.
Generally, I would like to ask you both to test most of the test cases of 3.4.8 of the FE functional tests of the test plan.
You can use the following hashes from the staging seed for the tests:
- QR-Code without Box: '168df347206ed26cd2213c0e4767ccb'
- QR-Code with Box in base 1: 'db7d22cebdc57632bfc0a23a504424b'
- QR-Code with Box in base 2: …

Resolve qr hash forwarded from dropapp

---

.circleci/config.yml
back/README.md
back/boxtribute_server/app.py
back/boxtribute_server/db.py
back/setup.cfg
back/test/conftest.py
back/test/model_tests/conftest.py
back/test/model_tests/test_utils.py
example.envrc

I implemented a custom class derived from peewee's `FlaskDB` to glue together Flask and the databases (the primary one and, for select-queries, the replica).
Further changes are about cleaning up env variables related to configure the DB connection locally and in CircleCI.

Enable DB replica

---

front/src/views/Transfers/ShipmentView/components/ShipmentActionButtons.tsx

The PR changes the style of the "Cannot Locate Shipment" button from ghost to outline.

ShipmentView: Change Style of Cannot Locat Shipment Button

---

front/src/types/generated/graphql.ts
front/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.tsx
front/src/views/Transfers/TransferAgreementOverview/TransferAgreementOverviewView.tsx

- fix caching on creation of new agreement
- return state on transfer agreement creation
Follow up from: https://github.com/boxwise/boxtribute/pull/1117

CreateShipment: Update Cache Object on Creation of New Agreement

---

back/boxtribute_server/graph_ql/filtering.py

See 4f22adc2d or https://github.com/coleifer/peewee/issues/2586 for
details.
This hopefully fixes excessive memory usage when the BE tries to fetch
and cache 100k of rows from the stock table.

Avoid triggering 'select * from stock'

---

.dockerignore
back/boxtribute_server/business_logic/warehouse/box/queries.py
back/boxtribute_server/graph_ql/pagination.py
back/gunicorn.conf.py

I inspected SQL generated by peewee, and profiled the stack of the app when executing the `boxes` GraphQL query while using a production DB dump.
- I could improve filtering of the select-query (filter on join instead of where)
- I added a filter for non-deleted boxes
- when a large result is queried, there will be overhead with both peewee and ariadne
- peewee as the ORM will have significant overhead transforming the raw SQL rows into Python objects (e.g. datetime parsing is quite costly)
- ariadne will issue an enormous amount of function calls to resolve the query fields (e.g. for each box the location and product), and since these make use of batch-loading, the eventual resolving of awaitables has an overhead, too
- smaller size of requested data (i.e. true pagination, only instock …

Inspect boxes-query performance

---

back/boxtribute_server/business_logic/statistics/crud.py
back/boxtribute_server/graph_ql/definitions/public/types.graphql
back/test/endpoint_tests/test_statistics.py
front/src/types/generated/graphql.ts
statviz/src/types/generated/graphql.ts

UPDATE: most of the BE implementation is replaced by SQL script in #1190 . The changes in the GraphQL interface remain.
Added productName, gender, sizeId, tagIds, and itemsCount to MovedBoxesResult

[6th viz] BE and GraphQL interface

---

back/README.md
back/boxtribute_server/app.py
back/boxtribute_server/business_logic/statistics/__init__.py
back/boxtribute_server/business_logic/statistics/crud.py
back/boxtribute_server/business_logic/statistics/queries.py
back/boxtribute_server/db.py
back/boxtribute_server/dev_main.py
back/test/conftest.py
back/test/integration_tests/test_operations.py

Follow-up to #1104.
When a GraphQL request contains a mutation, the database operations will be executed on the primary instance.
See commit messages for details.
This PR includes small improvements of the DatabaseManager, too.

Use DB replica only for GraphQL queries

---

back/README.md
back/boxtribute_server/app.py
back/boxtribute_server/routes.py
back/test/endpoint_tests/test_simple.py
docs/adr/adr_sizes-in-api.md
docs/graphql-api/full-api-config.yml
docs/graphql-api/query-api-config.yml

The old GraphQL playground was deprecated, long live GraphiQL explorer (see trello card).
Please check it out quickly: e.g. `localhost:5005/graphql`
It looks a bit different at first (but you can configure it to use a dark theme in the settings on the bottom left).

Use GraphiQL explorer

---

back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
back/boxtribute_server/exceptions.py
back/test/endpoint_tests/test_shipment.py

E.g. if given target location or product are not part of the target
base of the underlying shipment.
Previously this was silently ignored, giving the impression that the
updateShipmentWhenReceiving mutation succeeded.
Test e.g. with Shipment 1, and location 22 (part of base 3 but shipment target base is 2).
Or you test via the FE (steps to reproduce in Trello card).

Raise BadUserInput error for invalid box reconciliation input

---

front/src/queries/cache.ts

@HaGuesto 
the visualizations showed wired and wrong results (like products in the stock overview when grouped by sizes) because i forgot to copy the cache configuration to the front folder. This PR should fix it.

cache settings for statviz in front

---

back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
back/test/data/__init__.py
back/test/data/base.py
back/test/endpoint_tests/test_base.py
back/test/endpoint_tests/test_organisation.py
back/test/endpoint_tests/test_permissions.py
back/test/endpoint_tests/test_shipment.py
back/test/endpoint_tests/test_statistics.py
back/test/endpoint_tests/test_tag.py

First commit contains the actual change, the others are improvements in the test codebase for less code duplication and readability.

Update Box.lastModified fields when changing box state during transfer

---

back/boxtribute_server/graph_ql/definitions/public/types.graphql
back/test/endpoint_tests/test_statistics.py
front/src/types/generated/graphql.ts
shared-components/Statviz/Components/Visualizations/Stock/StockOverviewPie.tsx
shared-components/types/generated/graphql.ts

As per request of @maikneubert, for avoiding type-casting in FE.
All statviz-specific queries are affected, if you have to make changes to FE code you can push it here I suggest.

[statviz] Update GraphQL types

---

docs/adr/adr_cloudsql_networking
docs/adr/adr_cloudsql_networking.md

Draft ADR to document decision to leave CloudSQL networking config as-is with a public IP

ADR draft for CloudSQL networking

---

back/boxtribute_server/business_logic/warehouse/box/crud.py
back/boxtribute_server/business_logic/warehouse/box/fields.py
back/boxtribute_server/graph_ql/bindables.py
back/boxtribute_server/graph_ql/execution.py
back/boxtribute_server/graph_ql/loaders.py
back/boxtribute_server/models/utils.py
back/test/data/history.py
back/test/endpoint_tests/test_box.py

When formatting the messages of box history, batch-load for all requested boxes, and format using SQL joins (i.e. insert product, size, box state, location name), instead of iterating over each raw change and fetching property names.
The following query
```graphql
{
boxes(baseId: 27, paginationInput: {first: 500}) {
elements {
history {
id
user { id }
changes
changeDate
}
}
}
}
```
previously took ~8s and caused about 1800 DB calls.
Now it's <0.5s with 5 DB calls (3 due to pagination, 2 for the history and user batch-loaders).
Also found and fixed the bug that the `Box.history.user` field was missing a batch-loader call.
The generated SQL is somewhat like this (didnt replace all placeholders)
```sql
select
GROUP_CONCAT(`t1`.`id`) as `ids`,
GROUP_CONCAT(`t1`.`changedate`) as …
```

Use batch-loader for Box.history

---

back/boxtribute_server/business_logic/metrics/crud.py
back/boxtribute_server/business_logic/metrics/fields.py
back/boxtribute_server/graph_ql/definitions/protected/types.graphql
back/test/endpoint_tests/test_metrics.py
front/src/types/generated/graphql.ts

- superseded by movedBoxes query
- was incorrect anyways (no change of box state taken into account,
only last_modified_on date)
- box IDs had to be added to test case whenever a new test box was added

Remove redundant Metrics.movedStockOverview field

---

back/boxtribute_server/graph_ql/loaders.py
back/test/endpoint_tests/test_box.py

e.g. for Hermine's box with ID 26663 (and 65 history entries), the batch loader fails, causing all `history` fields to be returned as null.
Follow-up to #1233.
@MaikNeubert you could test it locally by running the webapp service connected to the prod DB via cloud SQL proxy, not sure if you've done it before.

Increase group_concat_max_len for BoxHistory loader

---

back/app-api.yaml
back/boxtribute_server/app.py
back/boxtribute_server/blueprints.py
back/boxtribute_server/db.py
back/boxtribute_server/routes.py
back/test/conftest.py

- Remove `/public` route from staging (not helpful since staging DB does not contain history data)
- Whitelist URL paths that need database connection (otherwise DB connection is opened for any route requested, causing errors like [here](https://boxwise.sentry.io/issues/5067454591/?environment=production&project=6584296&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0))
- Drop test databases at end of test session (improved clean-up)
- Define blueprints in separate module (more consistent)
- Remove Flask default route `/static/<filename>` (although not reachable due to our GAE configuration, it's not needed)

Tighten back-end security

---

back/boxtribute_server/authz.py
back/boxtribute_server/business_logic/warehouse/product/crud.py
back/boxtribute_server/business_logic/warehouse/product/mutations.py
back/boxtribute_server/errors.py
back/boxtribute_server/exceptions.py
back/boxtribute_server/graph_ql/bindables.py
back/boxtribute_server/graph_ql/definitions/basic/enums.graphql
back/boxtribute_server/graph_ql/definitions/protected/inputs.graphql
back/boxtribute_server/graph_ql/definitions/protected/mutations.graphql
back/boxtribute_server/graph_ql/definitions/protected/types.graphql
back/boxtribute_server/models/utils.py
back/test/auth.py
back/test/endpoint_tests/test_app.py
back/test/endpoint_tests/test_permissions.py
back/test/endpoint_tests/test_product.py
back/test/integration_tests/test_operations.py
back/test/model_tests/test_utils.py
back/test/unit_tests/test_authz.py
front/src/types/generated/graphql.ts

new:
- GraphQL interface for products (mutations, input types, etc.): [files in `graphql/definitions/`](https://github.com/boxwise/boxtribute/pull/1266/files#diff-78d6e340f0803294242d845e5d92985a7bbd1b5d95d4dc6af0818053594750549)
- implementation of `createCustomProduct` mutation incl. error handling (using error result defined via GraphQL schema)
[Test plan](https://docs.google.com/spreadsheets/d/1sDhSsaVwNxAhGn1VYACDPVepZpvlwTkgy9nmeTaRy2Q/edit?pli=1#gid=1709672082) has been updated.
- start with `mutations.graphql` and check `inputs.graphql` and `types.graphql` as references
- the mutation resolver is implemented in `.../product/mutations.py`, check authorization there
- the resolver calls into a function in `.../product/crud.py`, check validation and creation of database entries …

GraphQL interface for products

---

.circleci/config.yml
back/.gcloudignore
back/app.yaml
back/boxtribute_server/blueprints.py
back/boxtribute_server/cron/reseed_db.py
back/boxtribute_server/db.py
back/boxtribute_server/routes.py
back/cron.yaml
back/test/endpoint_tests/test_cron.py

Some logic taken from
https://github.com/boxwise/dropapp/blob/dc7fa2c608460115519dacd25d41dc051b559525/cron/reseed-db.php
Updated .gcloudignore to insure init.sql is present in the deployed GAE environment.
Also it seems the `reseed-db` PHP cron job does run after all: [cron logs](https://console.cloud.google.com/cloudscheduler?project=dropapp-242214) with [details](https://console.cloud.google.com/logs/query;query=protoPayload.taskName%3D%226729109412488123316%22%20protoPayload.taskQueueName%3D%22__cron%22;cursorTimestamp=2024-04-17T00:18:00.864919Z;aroundTime=2024-04-17T00:36:17.182Z;duration=PT1H?project=dropapp-242214)
Extend `.env` with
```bash
MYSQL_USER=root
MYSQL_HOST=127.0.0.1
MYSQL_PORT=32000
MYSQL_DB=dropapp_dev
MYSQL_PASSWORD=dropapp_root
```
and apply the following patch …

Enable cron-job to reseed staging DB

---

.circleci/config.yml
back/cron.yaml

Moved to system-management repo to deploy single file for dropapp and v2
cron jobs (otherwise deploying in either app overrides settings deployed
by other app)
Cf. boxwise/dropapp#588

Remove cron.yaml

---

docs/adr/adr_python-faking-stack.md

Rendered version: https://github.com/boxwise/boxtribute/blob/adr/python-stack-test-data-generation/docs/adr/adr_python-faking-stack.md

Add ADR about Python test data generation

---

README.md
back/README.md
back/test/integration_tests/test_cli.py

Likely caused by an improper teardown of a previous test run, e.g. due
to exceeding the Auth0 API rate limit which prevented proper deletion
of Auth0 test users

Fix readme and Auth0 integration tests

---

shared-components/statviz/dashboard/Dashboard.tsx

This PR implements a minor fix to resolve the issue with the Statviz filter overlay appearing on the menu.

Fix Statviz Filter zIndex

---

front/index.html

This PR temporarily disables the installation of PWAs by commenting out `manifest.js` since it hasn't been tested yet.

Fix: Disabling Install PWA on Client

---

back/boxtribute_server/business_logic/box_transfer/agreement/crud.py
back/boxtribute_server/business_logic/core/base/queries.py
back/boxtribute_server/business_logic/core/organisation/fields.py
back/boxtribute_server/graph_ql/definitions/protected/queries.graphql
back/boxtribute_server/graph_ql/definitions/protected/types.graphql
back/boxtribute_server/graph_ql/filtering.py
back/boxtribute_server/models/definitions/base.py
back/test/data/__init__.py
back/test/data/base.py
back/test/data/organisation.py
back/test/endpoint_tests/test_base.py
back/test/endpoint_tests/test_organisation.py
back/test/endpoint_tests/test_statistics.py
back/test/integration_tests/test_cli.py
back/test/model_tests/test_cli.py
front/src/types/generated/graphql.ts
front/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.tsx

Filtering is now possible with these two queries:
```graphql
organisations { bases(filterInput: {includeDeleted: false}) { id }}
bases(filterInput: {includeDeleted: false}) { id }
```
Default for the filter parameter is to _include_ deleted bases. I did it this way because I didn't want a `bases` query to have breaking-change behavior. There might be API users who rely on the `bases` query returning deleted bases, too; and there is our own FE that might issue the `bases` query in different places, and I didn't want to break it.
I adjusted the FE already.
Furthermore the `Base.deletedOn` field was added.

Enable filter for deleted bases

---

front/src/views/Boxes/BoxesView.test.tsx

I removed the tests out of the `forEach` so the functions can be hoisted. Hopefully, those specs won't time out again.
Got to handle the other flaky tests at some point, though.

Remove failing flaky tests from forEach loop

---

front/src/components/QrReader/QrReaderContainer.tsx

Chrome (mobile only) was catching the [MediaStream.NotReadableError](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#notreadableerror) because the camera wasn't loaded yet when the permission was evaluated. Thus showing an error toast.

Check only for not allowed or found MediaStream errors

---

.github/dependabot.yml

- group all dev updates, regardless of version bump
- group all prod updates with "patch" version bumps
- all other updates receive individual PRs

Introduce dependabot groups for BE dependency updates

---

.github/workflows/codeql-analysis.yml

Existing CodeQL was deprecated in Jan 2023 - https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

Bump CodeQL to v2 to remove deprecated warnings

---

.github/workflows/codeql-analysis.yml

CodeQL v1 was deprecated in Jan 2023

Bump CodeQL to v3 to remove deprecated warnings

---

back/boxtribute_server/business_logic/box_transfer/agreement/crud.py
back/boxtribute_server/business_logic/user/fields.py
back/boxtribute_server/graph_ql/definitions/protected/inputs.graphql
back/boxtribute_server/graph_ql/definitions/protected/mutations.graphql
back/boxtribute_server/graph_ql/definitions/protected/queries.graphql
back/boxtribute_server/graph_ql/definitions/protected/types.graphql
back/test/endpoint_tests/test_product_categories.py
front/src/types/generated/graphql.ts

I built the schema documentation that we host e.g. on api-staging.boxtribute.org/docs ([instructions](https://github.com/boxwise/boxtribute/blob/master/docs/graphql-api/README.md#usage)), and zipped it:
[docs.zip](https://github.com/user-attachments/files/16713998/docs.zip)
Extract and view `public/index.html`.

Update GraphQL schema documentation

---

.circleci/config.yml
.pre-commit-config.yaml

Previously achieved via a script (invoke_yarn) which seems unnecessary
in hindsight.
Follow-up for #1444.

Generate GraphQL Typescript definitions via pre-commit

---

shared-components/statviz/components/VisHeader.tsx
shared-components/statviz/utils/analytics/heap/types.ts

Extended heap tracking event with the image download type. 
Would have liked to add tests in this iteration but couldn't run tests for FE, see thread: https://boxwise.slack.com/archives/CB1UYDGLU/p1724450618067419?thread_ts=1724361187.607409&cid=CB1UYDGLU - will definitely add tests when I can address this.

Add tracking by image download type

---

back/boxtribute_server/business_logic/beneficiary/fields.py
back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
back/boxtribute_server/business_logic/warehouse/box/fields.py
back/boxtribute_server/business_logic/warehouse/location/fields.py
back/boxtribute_server/business_logic/warehouse/product/fields.py
back/boxtribute_server/graph_ql/definitions/protected/types.graphql
back/boxtribute_server/models/definitions/beneficiary.py
back/boxtribute_server/models/definitions/box.py
back/boxtribute_server/models/definitions/location.py
back/boxtribute_server/models/definitions/product.py
back/test/endpoint_tests/test_box.py
back/test/endpoint_tests/test_classic_location.py
back/test/endpoint_tests/test_permissions.py
back/test/endpoint_tests/test_product.py
front/src/types/generated/graphql.ts

- Use batched bulk creation for shipment details
- Account for alphabetically sorted label identifiers
- Extend docs about Box.location and Box.product
- Use batch-loading for createdBy and lastModifiedBy fields
- Extend test case

Minor fixes

---

shared-components/statviz/components/filter/TimeRangeSelect.tsx
shared-components/statviz/hooks/useMultiSelectFilter.ts
shared-components/statviz/hooks/useValueFilter.ts
shared-components/statviz/utils/analytics/heap/index.ts

Implemented filter tracking courtesy of Maik's draft implementation in https://github.com/boxwise/boxtribute/pull/1364/files#diff-ef01c5e03077013a4f49a11bf62dba2f8d1a35268b3f6438aa8bb1b1b5346461. 
As I couldn't test it locally due to errors in running the frontend, could @fhenrich33 take a peek at running this branch locally and see if the console logs log the correct filter values? 
Note: There is a slight deviation between Maik's changes in `shared-components/statviz/components/filter/TimeRangeSelect.tsx` and mine, see original version here- https://github.com/boxwise/boxtribute/pull/1364/files#diff-ef01c5e03077013a4f49a11bf62dba2f8d1a35268b3f6438aa8bb1b1b5346461L7.

Implement tracking of filter values

---

front/src/components/Table/Table.tsx

Key prop needs to be explicit, not exposed via a spread. These were causing errors in the console of the browser:
when accessing http://localhost:3000/bases/1/transfers/shipments

Fix console warning in browser re key usage

---

front/src/components/AreYouSure.tsx
front/src/components/Form/SelectField.tsx
front/src/components/QrReader/components/QrReaderScanner.tsx
front/src/components/Table/Table.tsx
front/src/views/Boxes/components/ActionButtons.tsx
shared-components/form/SelectField.tsx
shared-components/statviz/components/NoDataCard.tsx
shared-components/statviz/components/VisHeader.tsx
shared-components/statviz/components/filter/MultiSelectFilter.tsx
shared-components/statviz/components/filter/ValueFilter.tsx

React deprecated defaultProps back in 2019, and we're getting test warnings about it - https://github.com/facebook/react/pull/16210. This switches them to use JS default props instead.

Fix test warnings about deprecated defaultProps

---

front/src/tests/setupTests.ts

So we get meaningful errors in test console output like this:
`Missing field 'requestedOn' while writing result { "__typename": "TransferAgreement", "comment": "", "id": "1", "requestedBy": { "__typename": "User", "id": "1", "name": "some admin" }, "shipments": [], "targetBases": [ { "__typename": "Base", "id": "2", "name": "Thessaloniki" }, { "__typename": "Base", "id": "3", "name": "Samos" }, { "__typename": "Base", "id": "4", "name": "Athens" } ], "targetOrganisation": { "__typename": "Organisation", "id": "2", "name": "BoxCare" }, "state": "Accepted", "sourceBases": [ { "__typename": "Base", "id": "1", "name": "Lesvos" } ], "sourceOrganisation": { "__typename": "Organisation", "id": "1", "name": "BoxAid" }, "type": "SendingTo", "validFrom": "2023-01-26T00:00:00+00:00", "validUntil": …

Include full apollo error messages when running tests

---

front/src/components/QrReaderOverlay/QrReaderOverlay.test.tsx
front/src/tests/helpers.ts
front/src/views/QrReader/QrReaderMultiBox.test.tsx

These were causing `Warning: The current testing environment is not configured to support act(...)` errors in the test console output. The react testing library handles act() automatically and so these are not necessary.

Remove unnecessary use of act()

---

front/src/components/BoxReconciliationOverlay/BoxReconciliationOverlay.test.tsx
front/src/components/QrReaderOverlay/QrReaderOverlay.test.tsx
front/src/mocks/functions.ts
front/src/tests/test-utils.tsx
front/src/views/Box/BoxView.test.tsx
front/src/views/BoxEdit/BoxEditView.test.tsx
front/src/views/Boxes/BoxesView.test.tsx
front/src/views/Boxes/BoxesViewActions.test.tsx
front/src/views/QrReader/QrReaderMultiBox.test.tsx
front/src/views/QrReader/QrReaderMultiBoxAssignTags.test.tsx
front/src/views/QrReader/QrReaderMultiBoxAssignToShipment.test.tsx
front/src/views/QrReader/QrReaderMultiBoxMoveBox.test.tsx
front/src/views/QrReader/components/ResolveHash.test.tsx
front/src/views/Transfers/CreateShipment/CreateShipmentView.test.tsx
front/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.test.tsx
front/src/views/Transfers/ShipmentView/ShipmentView.test.tsx
shared-components/statviz/components/visualizations/movedBoxes/MovedBoxes.test.tsx

The current test set up intercepts GraphQL errors to print them as output. This is useful, as they warn about missing mock data and other errors. However, these messages are mixed up in 'expected' failures that we've set up in the tests themselves. 
This PR switches to separate classes for our fake errors so we can exclude them from the console output.

Stop logging expected GraphQL errors in test output

---

.circleci/config.yml
.vscode/launch.json
front/package.json
front/src/index.tsx
front/src/providers/ApolloAuth0Provider.tsx
pnpm-lock.yaml

The span id within transparent will not match, but the trace id itself will. Can review if/when Sentry support for traceparent https://github.com/getsentry/sentry-javascript/issues/11171#issuecomment-2408107582 progresses.

Align traceparent with Sentry's sentry-trace header

---

.circleci/config.yml

Better traceability in repository than the auto-generated date

Use git commit hash or tag as GCloud deploy version

---

back/boxtribute_server/authz.py
back/test/auth.py
back/test/auth0_integration_tests/test_operations.py
back/test/auth0_integration_tests/test_permissions.py
back/test/unit_tests/test_authz.py
back/test/utils.py

- all mutations can be controlled via beta-levels
- when a new mutation is added to the BE, it must be added to one beta-level
- when in development, the FE requests a new mutation using a test user, the mutation needs to moved to a smaller beta-level

Make all mutations available via beta-levels

---

front/src/components/HeaderMenu/HeaderMenuContainer.tsx

- Fix dropapp redirection for Checkout
- List Dashboard first in menu

Menu updates

---

.circleci/config.yml

@jamescrowley  Trying to fix the problem bellow when dependabot open PRs:
Trying this suggested fix https://github.com/pnpm/pnpm/issues/7934#issuecomment-2117539381

Fix package installation in CI

---

shared-components/statviz/components/filter/TimeRangeSelect.tsx
statviz/types/generated/gql.ts

This is a fix for the bug mentioned [here](https://trello.com/c/XUrjWcSI).
Reason for the error: The state was used and edited before passing the state to the state update function. This is not best practice and did somehow not work on the initial load.
@pylipp you wanted to create a bug ticket for it, could you assign this PR to it?

fix default timerange filter in statviz

---

front/src/queries/queries.ts
statviz/types/generated/gql.ts

since the ALL_SHIPMENTS_QUERY was just used in the shipments overview and does not need the recursive query of shipment detail, I only had to separate out the query from the existing fragment.
ALL FE tests passed locally

re-write ALL_SHIPMENTS query

---

.pre-commit-config.yaml
back/README.md

To avoid confusion on changes in e.g. readme files:
- Run trailing-whitespace pre-commit linter only on Python files
- Run pre-commit only on file changes in back/
FYI @fhenrich33

Make pre-commit operate more clearly

---

front/src/components/Table/TableHeader.tsx
front/src/views/Boxes/BoxesView.tsx

Changes:
In this PR I added a "Manage Boxes" page title to the "Manage Boxes" view, and also added breadcrumb navigation. 
Also made the table header sticky when scrolling. 
https://github.com/user-attachments/assets/22d76924-6fc5-471a-adab-f7d5b31f79d0

Implement Manage Boxes breadcrumbs and make table header sticky on scroll

---

docs/adr/adr_i18n.md

[Doc as rendered markdown](https://github.com/boxwise/boxtribute/blob/adr/i18n/docs/adr/adr_i18n.md).
Superceding [this doc](https://docs.google.com/document/d/1dVGQIl_8fO5_JDpVCg9g_GVG7Zl0sbx5VqUmAcV5VO0/edit?pli=1&tab=t.0#heading=h.mfo0lhwbjnsb).

Add i18n ADR

---

back/boxtribute_server/business_logic/warehouse/product/crud.py
back/boxtribute_server/business_logic/warehouse/product/fields.py
back/boxtribute_server/graph_ql/execution.py
back/boxtribute_server/graph_ql/loaders.py
back/test/endpoint_tests/test_product.py
front/src/views/Products/ProductsView.tsx

Only take certain box states into account in check of still being assigned to product

---

front/src/hooks/useLoadAndSetGlobalPreferences.ts

Handle god user without any base_ids in their auth token

---

front/src/hooks/useLoadAndSetGlobalPreferences.ts
front/src/views/Products/ProductsView.tsx

God user does not have base_ids set in their JWT, hence selectedBaseIdAtom keeps returning "0" which does not match the urlBaseId.
As a result, the skeletons that use selectedBaseAtom load forever (e.g. in EnableStandardProductForm).

Make base-name skeletons load for god user

---

front/src/views/Boxes/components/RemoveTagsButton.tsx

As the title describes. Currently if 2 boxes are selected and one of them has tags but the other has 0, when the box with tags gets unchecked, leaving only one box selected, the dropdown doesnt render 0 tags (which is expected behavior). 
This commit fixes that.

BUG FIX for unassigntags - No tags should get rendered if tagless box is selected

---

back/boxtribute_server/business_logic/beneficiary/crud.py
back/test/endpoint_tests/test_beneficiary.py

peewee then assumes there's a "registered" column if the first element
of the input array contains this key

Avoid confusing peewee with "registered" input

---

front/src/views/BoxEdit/components/BoxEdit.tsx

We've been observing errors that a `{"status":"aborted"}` input is
being passed as input into the updateBox mutation from the BoxEdit view
[sentry].
I found an issue in the GH repo of the zod validation library that we
use in the BoxEdit form [github1], [github2], and it hints that
`z.NEVER` should only be used after fatal parsing issues, as a somewhat
unreachable code to satisfy return type requirements.
I decided to remove the `nullable` option (not sure why it's being used
in the first place, since we DON'T want the numberOfItems to be null),
and then also the following `transform` which seemed to serve as a
catcher of null numberOfItems inputs (but I don't understand how they
can be given as input).
Cf. colinhacks/zod#2192
[sentry](https://boxwise.sentry.io/issues/4843084837/events/af3 …

Remove unnecessary validation for numberOfItems input in BoxEdit

---

front/src/views/EnableStandardProduct/EnableStandardProductView.tsx
front/src/views/EnableStandardProduct/components/EnableStandardProductForm.tsx

- Make breadcrumb navigation on EnableStandardProductView use absolute path (partially broken by myself in #2174)
- Fix cancel button navigation in EnableStandardProductForm
FYI @HaGuesto @fhenrich33

Update EnableStandardProduct back navigation

---

front/src/hooks/hooks.ts
front/src/views/BoxCreate/BoxCreateView.tsx

- Revert "Make IUseTableConfigProps.defaultTableConfig optional"
- Use defaultTableConfig when refetching boxesview data after creating box
FYI  @HaGuesto @fhenrich33 
Actually a follow-up for an edgecase of #2167 
Sentry: https://boxwise.sentry.io/issues/6623399559/?project=6584301&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0

Fix create box if not having visited BoxesView before

---

front/src/views/BoxCreate/BoxCreateView.tsx

Revert #2167 and #2176.
The memory load is too large for the GAE instance, we're seeing
gunicorn workers being terminated by GAE.

Remove refetching BOXES_FOR_BOXESVIEW_QUERY after creating box

---

back/boxtribute_server/business_logic/warehouse/box/queries.py
back/boxtribute_server/graph_ql/pagination.py

When loading the first 20 InStock boxes:
After loading of all InStock boxes:

Order result of boxes query by last_modified_on

---

front/src/mocks/products.ts
front/src/mocks/shipmentDetail.ts
front/src/views/Transfers/ShipmentView/ShipmentView.test.tsx
front/src/views/Transfers/ShipmentView/ShipmentView.tsx
front/src/views/Transfers/ShipmentView/components/ShipmentTabs.tsx

- Update confusing naming
- Correctly set up shipment detail test data
- Show correct box sizes when grouping by product in ShipmentView
- Remove 'Missing field' warning when creating mock data

Correctly show box sizes grouped by product in ShipmentView

---

back/boxtribute_server/logging.py
back/boxtribute_server/routes.py
back/test/endpoint_tests/test_app.py

- Log GraphQL query execution time to GCloud
- Add logging test for requests to query-API
- Use distinct context name for requests to public endpoint

add query execution time to gcloud logging

---

back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
back/test/endpoint_tests/test_shipment.py

https://trello.com/c/uUaagOoO/1807-20-bug-multiple-history-entries-when-repeatedly-adding-removing-box-to-from-shipment

Avoid redundant history entries when repeatedly adding/removing box to/from shipment
