- CONTRIBUTING.md
- README.md
I created a document to summarize most of the questions I heard in the last few weeks. 
It is a mix of FAQ for new people on how we work and best practices.
It is partly based on the [Contribution guidelines of the old repo](https://github.com/boxwise/dropapp/blob/master/CONTRIBUTING.md).
Instead of putting this just in front of you, I would really like to hear your opinion. Please take a look.
> Add Contribution Guidelines

- flask/README.md
Not going too much into detail to avoid duplicating the peewee-moves documentation
> Update README for peewee-moves

- .circleci/config.yml
- .pre-commit-config.yaml
- flask/boxwise_flask/auth_helper.py
- flask/boxwise_flask/models/beneficiary.py
- flask/boxwise_flask/models/box.py
- flask/boxwise_flask/models/history.py
- flask/boxwise_flask/models/product.py
- flask/boxwise_flask/routes.py
- flask/requirements-dev.txt
- flask/test/auth.py
Previously when committing, pre-commit failed locally with an error message
Directory '.' not installable, no setup.py found
In CircleCI the style checks were not enabled, hence a couple of irregularly formatted code parts were already in the code base.
> Enable Python pre-commit hooks

- flask/boxwise_flask/graph_ql/operations.graphql
- flask/boxwise_flask/graph_ql/pagination.py
- flask/boxwise_flask/graph_ql/resolvers.py
- flask/boxwise_flask/graph_ql/types.graphql
- flask/test/endpoint_tests/test_app.py
- flask/test/endpoint_tests/test_beneficiary.py
- flask/test/endpoint_tests/test_permissions.py
- flask/test/endpoint_tests/test_product.py
Full pagination support is here!
Highlights:
- backwards pagination (before and last parameters), computation of hasPreviousPage
- add pagination for Location.boxes field
- add pagination for products field and query
- Implement totalCount field for *Page GraphQL types
Let me know if anything is unclear =)
> GraphQL pagination follow-up

- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/graph_ql/types.graphql
- back/boxtribute_server/models/crud.py
- back/boxtribute_server/models/definitions/beneficiary.py
- back/boxtribute_server/models/definitions/location.py
- back/test/data/__init__.py
- back/test/data/beneficiary.py
- back/test/data/box.py
- back/test/data/location.py
- back/test/data/product.py
- back/test/data/product_category.py
- back/test/endpoint_tests/test_base.py
- back/test/endpoint_tests/test_beneficiary.py
- back/test/endpoint_tests/test_box.py
- back/test/endpoint_tests/test_location.py
- back/test/endpoint_tests/test_organisation.py
- back/test/endpoint_tests/test_permissions.py
- back/test/endpoint_tests/test_product.py
- back/test/endpoint_tests/test_product_categories.py
- back/test/endpoint_tests/test_qr.py
- back/test/endpoint_tests/test_user.py
- back/test/integration_tests/test_box.py
Small fixes, please see commit messages for details.
> Small GraphQL enum fix

- back/Dockerfile
- back/README.md
- back/gunicorn.conf.py
- back/scripts/load-test.js
- docker-compose.yml
closes https://trello.com/c/yZXAchvk/810-fix-docker-app-setup-for-macs
> 810 fix app setup with docker on mac and upgrade mysql to v8.0

- react/src/utils/test-utils.tsx
- react/src/views/locations/Locations.test.tsx
- react/src/views/locations/Locations.tsx
contributes to https://trello.com/c/CYiylASq/825-add-basic-test-for-skeleton-for-fe-app
> 825 - add some first basic tests to locations view

- .circleci/config.yml
related to https://github.com/boxwise/dropapp/pull/466
> staging-explorations: add tmp enviornment

- docker-compose.yml
- react/codegen.yml
- react/package.json
- react/src/generated/graphql.tsx
- react/src/views/locations/BTLocation.tsx
- react/yarn.lock
* based on https://www.graphql-code-generator.com
Closes https://trello.com/c/zfnLBWnm/852-add-automated-graphql-ts-types-generation
> 852 - Add automated graphql->ts-types generation

- back/README.md
- back/boxtribute_server/auth.py
- back/boxtribute_server/authz.py
- back/boxtribute_server/box_transfer/agreement.py
- back/boxtribute_server/box_transfer/shipment.py
- back/boxtribute_server/exceptions.py
- back/boxtribute_server/graph_ql/inputs.graphql
- back/boxtribute_server/graph_ql/mutations.graphql
- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/models/crud.py
- back/test/auth_tests/test_authz.py
- back/test/endpoint_tests/test_app.py
- back/test/endpoint_tests/test_box.py
- back/test/endpoint_tests/test_permissions.py
- back/test/integration_tests/test_operations.py
- back/test/model_tests/test_crud.py
- react/src/generated/graphql.tsx
This PR brings a couple of small improvements for the back-end coding environment.
Please see individual commits for details and feel free to come back with questions :)
> Backend code enhancements

- .circleci/config.yml
- back/README.md
- back/app.yaml
- back/boxtribute_server/main.py
- back/boxtribute_server/routes.py
- react/src/index.tsx
Please test that login and logout work at https://v2-staging.boxtribute.org
@spaudanjo I'm not sure where/if the env variables `REACT_APP_REDIRECT` and `REACT_APP_LOGOUT_URL` are used in the FE code at all?
> Fix frontend deploy

- back/app.yaml
things favicon.ico, robotos.txt, manifest.json might also be needed to add
> Add route for static files

- react/package.json
- react/src/App.tsx
- react/src/components/HeaderMenu.tsx
- react/src/components/QrScanner.tsx
- react/src/types/generated/graphql.ts
- react/src/views/Box/Box.tsx
- react/src/views/Boxes/Boxes.tsx
- react/src/views/Boxes/components/BoxesTable.tsx
- react/src/views/Boxes/components/Checkbox.tsx
- react/src/views/Boxes/components/GlobalFilter.tsx
- react/src/views/Boxes/components/types.ts
- react/yarn.lock
* Adding QR Code Scanner
* Add Box Detail view
* Boxes List view
* Prepare Select Checkboxes
* Make rows clickable (directs to respective Box Detail view)
* Add tests
* Add special logic for Non-Boxtribute-QR-Codes
* Redirect to a new `Create new Box` view for Boxtribute QR-Codes which are not yet linked to a box
* Improve (more boxtribute specific) regex
> Qr code scanner

- docs/graphql-api/README.md
- docs/graphql-api/full-api-config.yml
Hej folks,
I took the chance to update the docs for the full API a little.
Please see the instructions in `docs/graphql-api/README.md` and build the docs for the full API locally. Let me know how it goes :)
> Update full API docs

- react/.eslintignore
- react/src/views/BTLocations/BTLocations.test.tsx
- react/src/views/Box/Box.tsx
Remove unused imports and add eslintignore
> Remove unused imports

- back/boxtribute_server/models/definitions/box.py
> small hint that Box 'comments' field should be nullable

- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/graph_ql/types.graphql
- back/test/data/product.py
- back/test/data/size.py
- back/test/data/size_range.py
- back/test/endpoint_tests/test_box.py
- back/test/endpoint_tests/test_product.py
- docs/adr/adr_sizes-in-api.md
- react/src/types/generated/graphql.ts
- react/src/views/Box/BoxView.tsx
- react/src/views/Box/components/BoxDetails.tsx
- react/src/views/BoxEdit/BoxEditView.tsx
- react/src/views/BoxEdit/components/BoxEdit.tsx
- react/src/views/Boxes/BoxesView.tsx
Ticket: https://trello.com/c/T9fnp1qX/917-rework-sizes-in-graphql-api
This implements [Option 2 from the Slack discussion](https://boxwise.slack.com/archives/CB1UYDGLU/p1654417142972759?thread_ts=1654342114.644239&cid=CB1UYDGLU)
> Sizes refactoring

- .gitignore
- back/boxtribute_server/graph_ql/types.graphql
- back/test/data/location.py
- back/test/endpoint_tests/test_location.py
Closes https://trello.com/c/FZdEC8zm/918-add-isstockroom-flag-to-location-type
> Add is stockroom flag to Location GraphQL type

- react/src/components/HeaderMenu/HeaderMenu.stories.tsx
- react/src/components/HeaderMenu/HeaderMenuMobile.tsx
* remove unused Story
* fix menu display issue (dynamic show/hide was only having effect for certain viewport range)
> [Mobile Distro Prototyping] Fix new menu issues

- back/README.md
- back/boxtribute_server/auth.py
- back/boxtribute_server/exceptions.py
- back/boxtribute_server/models/crud.py
- back/boxtribute_server/models/definitions/beneficiary.py
- back/test/data/base.py
- back/test/data/beneficiary.py
- back/test/data/box.py
- back/test/data/location.py
- back/test/data/product.py
- back/test/data/shipment_detail.py
- back/test/data/tag.py
- back/test/data/tags_relation.py
- back/test/data/transaction.py
- back/test/endpoint_tests/test_beneficiary.py
- back/test/endpoint_tests/test_box.py
Relevant/helpful for anyone working with the back-end @spaudanjo @flisowna:
- Explain how to inspect peewee SQL queries in webapp docker-compose service
- Explain how to circumvent auth logic for app testing
Please have a look at the readme updates.
Also enhancing some tests and handling missing custom permissions claim in JWT (avoiding incomprehensive errors when using the JWT of a user who doesn't have a role assigned in Auth0).
> Various improvements

- .circleci/config.yml
- back/boxtribute_server/auth.py
- back/boxtribute_server/main.py
- back/requirements.txt
- back/setup.cfg
Produce an error in https://v2-staging.boxtribute.org (e.g. request to show non-existing box), then head to https://sentry.io/organizations/boxwise/issues/?project=1217716 and check for a new issue (it might be grouped with similar older ones).
> Integrate sentry SDK in backend

- .circleci/config.yml
- back/boxtribute_server/auth.py
- back/boxtribute_server/main.py
- back/requirements.txt
- back/setup.cfg
Reverting #306, since #303 was not faulty in the first place
> Re-integrate sentry into backend

- docs/adr/adr_sizes-in-api.md
Contributes to [Trello Card 917-rework-sizes-in-graphql-api](https://trello.com/c/T9fnp1qX/917-rework-sizes-in-graphql-api)
> Update sizes adr

- react/src/views/Boxes/components/BoxesTable.tsx
CircleCI failed on master:
https://app.circleci.com/pipelines/github/boxwise/boxtribute/1509/workflows/16b303e2-b618-4483-b086-c47f197d7a71/jobs/6591
> Remove unused import

- react/src/views/Boxes/BoxesView.test.tsx
Was introduced with 19d0f49dffabaf3b78a6e640abfd4909d5cbddf7
Focus is at the moment on prototyping and having a user-testable version ready. Automated test will to be updated/extended once features are confirmed as stable by user testing.
> FE: deactivate failing Boxes List view tests temporary

- back/boxtribute_server/graph_ql/resolvers.py
- back/test/data/tag.py
- back/test/endpoint_tests/test_permissions.py
- back/test/endpoint_tests/test_user.py
- back/test/integration_tests/test_operations.py
This PR brings some updates regarding authz before the production-merge for Boxtribute 2.0
Please see the attached trello card and the commit messages for context.
FYI @aerinsol
> Update permission enforcement

- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/models/crud.py
- back/test/endpoint_tests/test_app.py
- back/test/endpoint_tests/test_permissions.py
- back/test/endpoint_tests/test_tag.py
- Implement deleteTag mutation
- Add test case ID
- Enforce authz and verify error handling for deleteTag mutation
> Tags mutations part 2

- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/loaders.py
- back/boxtribute_server/models/definitions/size.py
- back/boxtribute_server/routes.py
- back/scripts/load-test.js
Enhance performance for query on BoxCreateView.
Local testing shows an decrease from 2.2s to 0.4s.
> Add DataLoader for size range sizes

- .circleci/config.yml
- README.md
This reverts commit 129b1f3b7b1cb2ac35069015d2e2ab843c29418b.
> Revert "disable API deployment in CircleCI"

- back/requirements.txt
- docs/graphql-api/package.json
- react/package.json
- react/src/App.tsx
- react/src/types/generated/graphql.ts
- react/src/views/Distributions/CreateDirectDistributionEventView/CreateDirectDistributionEventView.tsx
- react/src/views/Distributions/CreateDirectDistributionEventView/components/CreateDirectDistributionEvent.tsx
- react/src/views/Distributions/DistributionReturnTrackings/DistrosReturnTrackingGroupView/DistrosReturnTrackingGroupView.tsx
- react/src/views/Distributions/DistroEventView/components/DistroEventContainer.tsx
- react/src/views/Distributions/DistroEventView/components/State2Packing/DistroEventDetailsForPackingStateContainer.tsx
- react/src/views/Distributions/DistroEventView/components/State4ReturnTrackingInProgress/DistroEventDetailsForReturnTrackingInProgressStateContainer.tsx
- react/src/views/Distributions/DistrosDashboardView/DistrosDashboardView.tsx
- react/src/views/Distributions/DistrosDashboardView/components/DistributionList.tsx
- react/src/views/Distributions/components/DistributionEventTimeRangeDisplay.tsx
- react/yarn.lock
Contributes to https://trello.com/c/rxoCBpSz/934-extend-new-fe-for-mobile-distribution-prototype-related-features
- new view for create direct distro event which allows to create distro event from the distro events view and not the distro spot
> create direct distro event view

- .circleci/config.yml
- README.md
- back/README.md
- back/boxtribute_server/auth.py
- back/scripts/load-test.js
- back/test/auth_tests/test_authz.py
- docker-compose.yml
- react/src/types/generated/graphql.ts
Various enhancements and fixes, please see commit messages.
Most importantly the trello card linked below.
If this is merged together with #388, I'll deploy v2.0.4 to have the query API live again.
> Prepare for another deploy

- react/src/App.tsx
- react/src/components/HeaderMenu/HeaderMenuContainer.tsx
We deactivate the Prototype of the 'Create Box' feature for now in the new FE.
> deactivate 'Create Box' in FE

- back/boxtribute_server/routes.py
This fixes the warnings shown in CircleCI.
Please see description in Trello card below.
> Use asyncio.run to execute graphql coroutine

- back/boxtribute_server/exceptions.py
- back/boxtribute_server/models/crud.py
- back/test/endpoint_tests/test_box.py
- react/src/types/generated/graphql.ts
Please see the description of the attached trello card.
> Validate numberOfItems input when creating/updating box

- .circleci/config.yml
- README.md
- back/Dockerfile
- back/README.md
- back/app-api.yaml
- back/app.yaml
- back/boxtribute_server/api_main.py
- back/boxtribute_server/app.py
- back/boxtribute_server/main.py
- back/gunicorn.conf.py
- back/setup.cfg
- docker-compose.yml
Please see the attached Trello card for an introduction.
I also updated the [deployment guide](https://docs.google.com/document/d/1zfqQ4yRUf4C-fbhMWfzKzBWPoDAvt4tF8nVI8fIrQrY/edit#) where needed.
@haguesto before merging this, I'd like to do a production deploy of v2 (to have established changes published first; then deploy again with the new CircleCI config which can result in some extra work for fixes).
Another thing we could consider is having a dedicated sentry project for the API.
> Separate workflows for webapp and query-API deployment in CircleCI

- react/src/views/Box/BoxView.tsx
- react/src/views/Box/components/BoxDetails.tsx
In this PR, changes are made to the BoxView component to display tags.
> Show Tags on BoxView

- react/.eslintignore
- react/.prettierignore
- react/package.json
- react/src/views/BoxEdit/BoxEditView.tsx
- react/src/views/BoxEdit/components/BoxEdit.tsx
This PR applies formatting and linting to BoxEdit as well as adding changes to the .eslintignore and .prettierignore setting
Follow up: https://github.com/boxwise/boxtribute/pull/436
> Apply linting/formatting to BoxEdit

- react/src/components/NotificationMessage.tsx
- react/src/index.tsx
- react/src/utils/hooks.ts
- react/src/utils/theme.ts
In this PR, a custom toast hook and global component are included for displaying notification messages. A separate file is also created for theme in this PR
> Make notification message global

- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/graph_ql/types.graphql
- back/test/auth.py
- back/test/endpoint_tests/test_permissions.py
- react/src/types/generated/graphql.ts
- react/src/views/Box/components/BoxDetails.tsx
Please see the attached trello card and commit messages.
> Revisit enforcement of resource based permissions on tags

- back/boxtribute_server/graph_ql/resolvers.py
- back/test/data/__init__.py
- back/test/data/box.py
- back/test/data/qr_code.py
- back/test/endpoint_tests/test_classic_location.py
- back/test/endpoint_tests/test_metrics.py
- back/test/endpoint_tests/test_permissions.py
- back/test/endpoint_tests/test_qr.py
This is a security fix, see attached Trello card for details.
> Prevent access to tagged beneficiaries data through QrCode.box.tags field

- back/boxtribute_server/authz.py
- back/boxtribute_server/exceptions.py
- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/graph_ql/types.graphql
- back/test/auth_tests/test_authz.py
- back/test/data/__init__.py
- back/test/data/transfer_agreement_detail.py
- back/test/data/user.py
- back/test/endpoint_tests/test_permissions.py
- back/test/endpoint_tests/test_transfer_agreement.py
- back/test/endpoint_tests/test_user.py
The final update... mostly updating transfer agreement resolvers.
> Update permissions enforcement part III

- back/boxtribute_server/auth.py
- back/boxtribute_server/authz.py
- back/boxtribute_server/routes.py
- back/test/auth_tests/test_authz.py
- back/test/integration_tests/test_permissions.py
- Check user beta feature scope when processing request to webapp back-end
- Add integration test for beta-feature access
> Implement access control for beta features

- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/graph_ql/types.graphql
- back/test/data/__init__.py
- back/test/data/product.py
- back/test/data/tag.py
- back/test/endpoint_tests/test_base.py
- back/test/endpoint_tests/test_product.py
- react/src/types/generated/graphql.ts
See attached trello card for how to adjust the FE query.
> Add tags field for GraphQL type Base

- .circleci/config.yml
- react/src/index.tsx
https://create-react-app.dev/docs/adding-custom-environment-variables/
Follow-up to #302 and #401.
> Prefix react app env variable to be recognized

- react/.eslintignore
- react/src/components/Layout.tsx
- react/src/components/NotificationMessage.tsx
- react/src/providers/ApolloAuth0Provider.tsx
- react/src/views/Box/BoxView.tsx
- react/src/views/BoxEdit/BoxEditView.tsx
- react/src/views/BoxEdit/components/BoxEdit.tsx
In the PR, error/success notification messages are handled consistently using a unified handler as follows:
- A local variable is created using the Apollo client
- Include a unify message handler in the layout
- Add a title to the notification message component
- update the error/success messages in the box edit and box view
> BoxView/BoxEdit: implement Error Handling

- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/graph_ql/types.graphql
- back/boxtribute_server/models/definitions/product.py
- back/test/data/__init__.py
- back/test/data/location.py
- back/test/data/product.py
- back/test/endpoint_tests/test_base.py
- react/src/types/generated/graphql.ts
> Filter deleted products and locations for base

- back/boxtribute_server/graph_ql/resolvers.py
See commit message for details.
Follow-up to #502.
> Work-around for zero datetime products.deleted field in database

- back/README.md
- back/boxtribute_server/beneficiary/crud.py
- back/boxtribute_server/beneficiary/fields.py
- back/boxtribute_server/beneficiary/mutations.py
- back/boxtribute_server/beneficiary/queries.py
- back/boxtribute_server/graph_ql/bindables.py
- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/graph_ql/schema.py
- back/boxtribute_server/models/crud.py
- back/boxtribute_server/user/fields.py
- back/boxtribute_server/user/queries.py
This is the start of the BE business logic refactoring. For an overview, see the Trello card and the README extension.
I'll add more refactoring PRs one-by-one. The current PR is ready for review but I'll leave it as draft because we don't need it for the production release.
> Modular resolver structure

- back/boxtribute_server/core/base/crud.py
- back/boxtribute_server/core/base/fields.py
- back/boxtribute_server/core/base/queries.py
- back/boxtribute_server/core/organisation/fields.py
- back/boxtribute_server/core/organisation/queries.py
- back/boxtribute_server/core/product_category/fields.py
- back/boxtribute_server/core/product_category/queries.py
- back/boxtribute_server/core/size_range/fields.py
- back/boxtribute_server/graph_ql/bindables.py
- back/boxtribute_server/graph_ql/resolvers.py
- back/boxtribute_server/metrics/crud.py
- back/boxtribute_server/metrics/fields.py
- back/boxtribute_server/metrics/queries.py
- back/boxtribute_server/tag/crud.py
- back/boxtribute_server/tag/fields.py
- back/boxtribute_server/tag/mutations.py
- back/boxtribute_server/tag/queries.py
- back/test/auth.py
- back/test/data/__init__.py
- back/test/data/distribution_event.py
- back/test/endpoint_tests/test_app.py
- back/test/endpoint_tests/test_base.py
- back/test/endpoint_tests/test_permissions.py
Moving resolvers into the structure
```
core/
base/
organsation/
product_category/
size_range/
tag/
```
Also adding test coverage for distro-event resolvers (thus fixing a broken one).
> Modular resolver structure pt. 2

- back/boxtribute_server/box_transfer/agreement/crud.py
- back/boxtribute_server/box_transfer/agreement/fields.py
- back/boxtribute_server/box_transfer/agreement/mutations.py
- back/boxtribute_server/box_transfer/agreement/queries.py
- back/boxtribute_server/box_transfer/shipment.py
- back/boxtribute_server/box_transfer/shipment/crud.py
- back/boxtribute_server/box_transfer/shipment/fields.py
- back/boxtribute_server/box_transfer/shipment/mutations.py
- back/boxtribute_server/box_transfer/shipment/queries.py
- back/boxtribute_server/graph_ql/bindables.py
- back/boxtribute_server/graph_ql/resolvers.py
Move resolvers into structure 
```
box_transfer/
agreement/
crud.py
fields.py
mutations.py
queries.py
shipment/
crud.py
fields.py
mutations.py
queries.py
```
> Modular resolver structure pt. 3

- react/src/views/BoxEdit/BoxEditView.tsx
See https://sentry.io/organizations/boxwise/issues/3820241539l
> Update box success notification for deleted products

- react/src/components/Form/NumberField.tsx
- react/src/views/Box/BoxView.tsx
- react/src/views/Box/components/AddItemsToBoxOverlay.tsx
- react/src/views/Box/components/TakeItemsFromBoxOverlay.tsx
In this PR, the items overlay is validated and the input field is changed to a number.
> BoxView: validate input of AddItemsOverlay TakeItemsOverlay

- react/src/components/Form/SelectField.tsx
- react/src/utils/helpers.ts
- react/src/views/Box/components/BoxDetails.tsx
- react/src/views/BoxCreate/components/BoxCreate.tsx
- react/src/views/BoxEdit/components/BoxEdit.tsx
The PR adds colors to tag options for tags that already have colors.
> BoxEdit/BoxView/BoxCreate: Add Colors to the Tag Options

- back/boxtribute_server/auth.py
- fetch_token
In combination with boxwise/system-management#1
> Auth0 Management API user import-export scripts

- back/requirements-dev.txt
> Update typing packages

- back/boxtribute_server/business_logic/box_transfer/shipment/crud.py
- back/test/endpoint_tests/test_shipment.py
Previously, the shipment was marked as Completed
> Mark shipment as Lost if all boxes marked as Lost

- react/src/components/HeaderMenu/HeaderMenuMobile.tsx
- react/src/components/QrReaderOverlay/QrReaderOverlay.test.tsx
The PR incorporates QR scanning into the mobile menu
> Incorporate QR Scan Into Mobile Menu

- react/src/components/HeaderMenu/HeaderMenuDeskop.tsx
- react/src/components/HeaderMenu/HeaderMenuMobile.tsx
- react/src/utils/helpers.ts
This PR fixes the logout issue for V2 apps that don't log out DropApp.
This [PR](https://github.com/boxwise/dropapp/pull/548) must be merged and deployed before this one
> Fix Logout Issue for V2 that Doesn't Logout DropApp

- react/src/components/HeaderMenu/HeaderMenuMobile.tsx
This PR is the first iteration to simplify the mobile menu and use the Chakra standard menu components
> Mobile Menu: First Iteration Using Chakra UI Menu Components

- back/test/auth.py
- back/test/endpoint_tests/conftest.py
- back/test/endpoint_tests/test_app.py
- back/test/endpoint_tests/test_box.py
- back/test/endpoint_tests/test_distribution_event_tracking_group.py
- back/test/endpoint_tests/test_metrics.py
- back/test/endpoint_tests/test_permissions.py
- back/test/endpoint_tests/test_shipment.py
- back/test/endpoint_tests/test_transfer_agreement.py
- back/test/endpoint_tests/test_user.py
Hide away the use of the jose library
> Add dedicated fcuntion for user-mocking in tests

- back/boxtribute_server/business_logic/box_transfer/shipment/fields.py
- Use batch-loading for ShipmentDetail.source/targetSize
- Join with Shipment model in Shipment.details resolver
> Improve query performance

- back/boxtribute_server/business_logic/statistics/crud.py
- back/boxtribute_server/graph_ql/definitions/public_api.graphql
- back/test/endpoint_tests/test_statistics.py
Follow-up for #893.
`beneficiaryDemographics` now returns a `{"facts": [...]}` data structure.
Definition in #888 is updated.
> [1st viz] beneficiary demographics facts dimensions structure

- react/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.test.tsx
- react/src/views/Transfers/CreateTransferAgreement/CreateTransferAgreementView.tsx
This PR add alert on identical agreement and implement test case 4.1.5.
> CreateTransferAgreementView: Alerts on Identical Agreements

- react/src/mocks/shipments.ts
- react/src/views/Transfers/ShipmentView/ShipmentView.test.tsx
- react/src/views/Transfers/ShipmentView/components/ShipmentContent.tsx
- react/src/views/Transfers/ShipmentView/components/ShipmentTable.tsx
- react/src/views/Transfers/ShipmentView/components/ShipmentTabs.tsx
The PR fixes the number of items shown per box in the shipment, and adds new test cases 4.5.1.6 to check the count and number of items are correct.
> ShipmentView: Fix the Number of Items Shown on Each Box in the Shipment

- react/src/views/Transfers/ShipmentView/ShipmentView.test.tsx
- react/src/views/Transfers/ShipmentView/components/ShipmentCard.tsx
The PR Fix displays the incorrect number of boxes for completed shipments and updates test case 4.5.5.
> ShipmentView: Fix Showing Incorrect Total Boxes Count for Completed Shipments

- react/src/views/Transfers/ShipmentView/components/ShipmentHistory.tsx
- react/src/views/Transfers/ShipmentView/components/ShipmentTabs.tsx
- fix time format in the shipment history
- fix history record status
> ShipmentView: Fix the Time Format and Make the Status More User-friendly

- react/src/views/Transfers/ShipmentView/ShipmentView.tsx
The PR corrects the message shown when a shipment is successfully sent.
> ShipmentView: Fix Successful Shipment Message Text

- back/boxtribute_server/graph_ql/filtering.py
- back/test/data/tags_relation.py
- back/test/endpoint_tests/test_box.py
- back/test/endpoint_tests/test_tag.py
> Avoid returning duplicate boxes when filtering for tag IDs

- back/boxtribute_server/business_logic/box_transfer/agreement/crud.py
Tested with BE running locally, logged [here](https://boxwise.sentry.io/issues/4535394176/?project=6584296&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) (I had to manually add the DSN when initializing the SDK).
This will not be effective during local testing.
> Emit warning to Sentry when multi-base agreement created

- back/boxtribute_server/business_logic/beneficiary/fields.py
- back/boxtribute_server/business_logic/statistics/crud.py
- back/boxtribute_server/models/utils.py
- back/test/endpoint_tests/test_statistics.py
Fixing issues I found after testing with production data.
> [1st viz] Fix beneficiary demographics for production data

- react/src/components/Form/SelectField.tsx
- react/src/components/Form/ShipmentOption.tsx
- react/src/components/QrReader/components/QrReaderMultiBox.tsx
- react/src/components/QrReader/components/QrReaderMultiBoxContainer.tsx
- react/src/components/QrReaderOverlay/QrReaderOverlay.test.tsx
- react/src/mocks/shipments.ts
- react/src/queries/queries.ts
- react/src/types/generated/graphql.ts
- react/src/views/Box/BoxView.tsx
- react/src/views/Box/components/AssignBoxToShipment.tsx
- react/src/views/BoxEdit/BoxEditView.test.tsx
- react/src/views/QrReader/QrReaderMultiBoxAssignToShipment.test.tsx
- react/src/views/Transfers/ShipmentsOverview/ShipmentsOverviewView.tsx
- add shipment id to query and shipment option
- add shipment id to boxview dropdown
- add shipment id to multibox qr reader dropdown
- add shipment id after base column in shipmentview
- Include shipment id in mocking data
- fix multibox qr reader tests
- add shipment id column before base column
- fix box edit test 3.2.7
> Implement New Shipment ID in FE

- front/src/views/Transfers/CreateShipment/CreateShipmentView.test.tsx
- front/src/views/Transfers/CreateShipment/CreateShipmentView.tsx
- fix error message when no agreement is available
- implement test case 4.3.4.2
> CreateShipment: Fix Error Message When No Accepted Agreement Available

- front/src/views/Boxes/BoxesView.test.tsx
- front/src/views/Boxes/components/BoxesActionsAndTable.tsx
- front/src/views/Boxes/components/BoxesTable.tsx
- wire up setSelectedBoxes to rows that checked
- implement test case 4.8.2.1
> BoxesActionsAndTable: Connect setSelectedBoxes to Checkboxes in Boxes Tables

- front/src/views/Transfers/CreateShipment/CreateShipmentView.test.tsx
- front/src/views/Transfers/CreateShipment/CreateShipmentView.tsx
- front/src/views/Transfers/TransferAgreementOverview/TransferAgreementOverviewView.tsx
- Alert style change to warning
- Fix caching problem
> CreateShipment: Fix to Show Alert When No Active Transfer Agreement Available

- front/src/views/Transfers/ShipmentView/ShipmentView.tsx
The PR adds padding to the bottom of the shipment view.
> ShipmentView: Add Padding to Bottom of Page

- front/src/views/Transfers/ShipmentView/components/ShipmentActionButtons.tsx
- front/src/views/Transfers/ShipmentView/components/ShipmentOverlay.tsx
- change button variant to outline
- change overlay text style
> ShipmentView: Button and Text Styling Changes

- front/src/components/BoxReconciliationOverlay/BoxReconciliationOverlay.test.tsx
- front/src/components/BoxReconciliationOverlay/components/MatchProductsForm.tsx
This PR updates the style and text of reconciliation UI, as well as correctly displaying source product gender.
> ReconciliationUI: Display Source Product Gender & Style Changes

- front/src/components/BoxReconciliationOverlay/BoxReconciliationOverlay.tsx
The AYS alert style has been fixed in this PR.
> BoxReconciliation: Fix AYS Alert Style

- back/boxtribute_server/models/utils.py
- back/test/endpoint_tests/test_beneficiary.py
With the beginning of the new year, all test-back jobs fail. This PR provides the fix.
> Fix age calculation

- back/boxtribute_server/business_logic/statistics/crud.py
Corresponding to the SQL below. Props to @HaGuesto for constructing it :rocket: 
I verified that the results are identical.
```sql
WITH ValidLocations AS  (
SELECT id 
FROM locations
WHERE camp_id = 11
)
SELECT 
ss.created_on,
COUNT(ss.id) as boxes_count,
SUM(ss.items) as items_count,
p.id as product_id,
p.gender_id as product_gender,
p.category_id as category_id
FROM (
SELECT 
DATE(s.created) as created_on,
s.id,
IFNULL(hi.from_int, s.items) as items,
-- COALESCE(hl.from_int, s.location_id) AS location_id,
IFNULL(hp.from_int, s.product_id) AS product_id
FROM 
stock s
LEFT JOIN history hl ON 
hl.record_id = s.id AND 
hl.tablename = 'stock' AND 
hl.changes = 'location_id' AND 
hl.id = (
SELECT MIN(hls.id)
FROM history hls
WHERE 
hls.record_id = s.id AND 
hls.tablename = 'stock' AND …
```
> [2nd viz] Improved version of createdBoxes SQL query

- back/boxtribute_server/business_logic/statistics/crud.py
- back/boxtribute_server/business_logic/statistics/sql.py
- back/boxtribute_server/models/definitions/history.py
- Move query part for shipped boxes
- Move query part for lost/scrap boxes
- Add comments
- Remove redundant IF/COALESCE
> [statviz] Finalize moved-boxes query

- docs/adr/adr_backend_etl_and_hosting_for_StatViz.md
[Rendered version](https://github.com/boxwise/boxtribute/blob/adr/statviz_backend/docs/adr/adr_backend_etl_and_hosting_for_StatViz.md)
> ADR for backend of DSEE 100x project with Hermine "Statviz"

- docs/adr/adr_gcloud-high-availability.md
[Rendered file](https://github.com/boxwise/boxtribute/blob/adr/gcloud-high-availability/docs/adr/adr_gcloud-high-availability.md)
> Add ADR about GCloud High Availability

- docs/adr/adr_graphql-error-responses.md
[Rendered version](https://github.com/boxwise/boxtribute/blob/adr/graphql-error-responses/docs/adr/adr_graphql-error-responses.md)
> ADR for more reliable GraphQL error response structure

- docs/auth/README.md
At the request of DPGA, adding docs regarding our Auth0 dependency.
> Add docs for Auth0 dependency

- back/boxtribute_server/business_logic/statistics/crud.py
- back/boxtribute_server/business_logic/statistics/sql.py
- back/test/data/box.py
- back/test/data/location.py
- back/test/endpoint_tests/test_box.py
- back/test/endpoint_tests/test_statistics.py
- Take archived locations and all boxes into account
- Take into account boxes created in Donated state
> [statviz] Fix accuracy issues of moved-boxes statistics

- back/boxtribute_server/app.py
- back/boxtribute_server/authz.py
- back/boxtribute_server/business_logic/mobile_distribution/crud.py
- back/boxtribute_server/business_logic/mobile_distribution/exceptions.py
- back/boxtribute_server/exceptions.py
- back/boxtribute_server/routes.py
- back/setup.cfg
- back/test/unit_tests/test_authz.py
- Update default beta-user level to 3
- Exclude mobile_distribution code from coverage analysis
- Use variable to indicate route path
> Update default beta-user level

- back/test/endpoint_tests/test_statistics.py
[test plan](https://docs.google.com/spreadsheets/d/1sDhSsaVwNxAhGn1VYACDPVepZpvlwTkgy9nmeTaRy2Q/edit?pli=1#gid=1709672082)
> [statviz] Reference authz test cases from test plan

- back/boxtribute_server/cron/reseed_db.py
- back/boxtribute_server/routes.py
- back/test/conftest.py
- back/test/endpoint_tests/test_cron.py
Instead of trying to use the mysql CLI which is not installed in the
Google App Engine environment. 
Follow-up to #1318.
> Fix cron-job to reseed staging DB

- back/.gcloudignore
- back/boxtribute_server/auth.py
- back/requirements.txt
- Revert "Debug public key"
- Update auth0-python package
- Extend gcloudignore
> Fix public key decoding error in v2-staging

- docs/assort/v1_20240523-products.md
[rendered document](https://github.com/boxwise/boxtribute/blob/docs/assort-products/docs/assort/v1_20240523-products.md)
Taken from [this sheet](https://docs.google.com/spreadsheets/d/17n82wl4obaf_9rcMg9fHW7i4Tf9Wavo2OCtdfhANcYc/edit#gid=1116346838), DB migration already effective [on staging](https://github.com/boxwise/dropapp/blob/master/db/migrations/20240523182223_populate_standard_products_table.php).
> Add first version of ASSORT products into docs

- README.md
- back/README.md
- back/boxtribute_server/business_logic/warehouse/standard_product/fields.py
- back/boxtribute_server/graph_ql/execution.py
- back/boxtribute_server/graph_ql/loaders.py
- back/scripts/load-test.js
- docs/peewee-moves/README.md
- front/README.md
- Use loader for StandardProduct.enabledForBases (more efficient to bulk select instead of selecting again for every standard product)
> Loader for StandardProduct.enabledBases

- back/README.md
- back/fetch_token
- back/scripts/load-test.js
- Move fetch_token script to back/
- Exit script with help message if no CLI args passed
- Document running fetch_token via docker-compose
FYI @HaGuesto @vahidbazzaz @fhenrich33 @jlin95 @MaikNeubert
> Improve fetch_token script

- docs/adr/adr_sync-async-back-end.md
https://github.com/boxwise/boxtribute/blob/adr/sync-async-backend/docs/adr/adr_sync-async-back-end.md
> ADR for sync-async backend

- back/README.md
- back/boxtribute_server/business_logic/statistics/crud.py
- back/boxtribute_server/business_logic/statistics/sql.py
- docker-compose.yml
How I validated the result:
1. Launch local webapp service connected to prod DB
1. Run the query
```graphql
{
movedBoxes(baseId: 43) {
facts {
movedOn
targetId
categoryId
productName
gender
sizeId
tagIds
itemsCount
boxesCount
}
}
}
```
3. Copy response JSON
4. Aggregate with `jq`
```sh
jq '[
.data.movedBoxes.facts[]
| select(.targetId == "Deleted")
| {movedOn, boxesCount, itemsCount}
] | group_by(.movedOn) | map({
movedOn: .[0].movedOn,
boxesCount: map(.boxesCount) | add,
itemsCount: map(.itemsCount) | add
})' data.json
```
5. Obtain result and validate against database with
```sql
select count(1) from (
select h.id, h.record_id , h.changes, h.changedate, s.items  from history h
inner join stock s
on s.id = h.record_id and h.tablename = "stock"
and DATE(h.changedate) = "2023-01-12"
-- and …
```
> include box deletion and undeletion in moved boxes statistics

- back/boxtribute_server/authz.py
- back/boxtribute_server/business_logic/mobile_distribution/exceptions.py
- back/boxtribute_server/business_logic/mobile_distribution/tracking_group/fields.py
- back/boxtribute_server/business_logic/warehouse/box/crud.py
- back/boxtribute_server/business_logic/warehouse/qr_code/crud.py
- back/boxtribute_server/exceptions.py
- back/boxtribute_server/graph_ql/loaders.py
- back/boxtribute_server/models/definitions/distribution_event.py
- back/boxtribute_server/models/definitions/distribution_event_tracking_log_entry.py
- back/boxtribute_server/models/definitions/distribution_events_tracking_group.py
- back/boxtribute_server/models/definitions/unboxed_items_collection.py
- back/requirements-dev.txt
- back/test/endpoint_tests/test_box.py
- docs/adr/adr_python-dev-env.md
> Back-end formatting and bug-linting

- back/test/integration_tests/test_cli.py
Prevents this test having issues if run concurrently against auth0
> Fix flakey Auth0 CLI test

- back/boxtribute_server/business_logic/box_transfer/agreement/fields.py
- back/boxtribute_server/graph_ql/definitions/protected/types.graphql
- back/test/data/transfer_agreement.py
- back/test/data/transfer_agreement_detail.py
- back/test/endpoint_tests/test_statistics.py
- back/test/endpoint_tests/test_transfer_agreement.py
- front/src/types/generated/graphql.ts
- Extend test data
- Exclude deleted bases from agreement source/targetBases field
> Exclude deleted bases from TransferAgreement.source/targetBases

- codecov.yml
Attempt to get codecov working as expected even when builds fail
> Add CodeCov configuration

- back/boxtribute_server/authz.py
- back/boxtribute_server/business_logic/beneficiary/mutations.py
- back/boxtribute_server/business_logic/mobile_distribution/event/fields.py
- back/boxtribute_server/business_logic/warehouse/box/mutations.py
- back/boxtribute_server/business_logic/warehouse/product/mutations.py
- back/setup.cfg
- back/test/auth.py
- back/test/endpoint_tests/test_app.py
- back/test/endpoint_tests/test_distribution_event_tracking_group.py
- docs/adr/adr_authorization-specification.md
after having checked out the Google permissions doc once more
> Update enforcement of resource-based permissions

- shared-components/statviz/components/VisHeader.tsx
- shared-components/statviz/utils/analytics/constants.ts
- shared-components/statviz/utils/analytics/heap/index.ts
- shared-components/statviz/utils/analytics/heap/types.ts
This is based off @MaikNeubert's implementation in this PR https://github.com/boxwise/boxtribute/pull/1364/files#. 
Need help with testing once it's deployed to staging?
This PR addresses: StatViz Image Downloads by Graph.
> First try at tracking downloads by format in statviz

- back/boxtribute_server/graph_ql/loaders.py
- back/test/endpoint_tests/test_box.py
> Exclude assigned-tag history entries at time of box creation

- back/gunicorn.conf.py
cf. https://www.joelsleppy.com/blog/gunicorn-application-preloading
> Use gunicorn preload

- front/package.json
- front/src/types/generated/graphql.ts
- pnpm-lock.yaml
Re-generated the graphql types. This is a dev dependency change only, and only affects type definitions.
> Update graphql-codegen to v4

- front/.storybook/main.ts
- front/package.json
- package.json
- pnpm-lock.yaml
Dev dependency that required update but we're not using so removing instead.
> Remove unused dev deps

- front/package.json
- front/src/index.tsx
- pnpm-lock.yaml
Reviewed change log for Sentry 8 and implemented required changes. This is a production change.
> Update to Sentry 8

- front/src/components/QrReader/QrReaderContainer.tsx
- front/src/components/Skeletons.tsx
> Add alert message about ios fix, fix qr reader skeleton size

- front/src/views/Transfers/CreateShipment/components/CreateShipment.tsx
accidentally removed by 54985fdb62cd23aaebdd35120dde026b843ca2d9
> Hide single-base org tab

- back/Dockerfile
- back/boxtribute_server/authz.py
- back/boxtribute_server/routes.py
- back/test/auth0_integration_tests/test_permissions.py
- back/test/conftest.py
- back/test/endpoint_tests/test_app.py
- Update beta-level check to enable fetching schema during development
- Use monkeypatch test fixture
> Update beta-level check to enable fetching schema during development

- back/requirements.txt
Reverts boxwise/boxtribute#1805
> Revert "build(deps): bump the back-prod-minor-update group in /back with 2 updates"

- front/src/components/QrReader/components/QrReaderMultiBox.tsx
This PR updates the move-to-location icon
> Update the icon for the "Move to Location"

- front/src/components/HeaderMenu/BaseSwitcher.tsx
- front/src/components/HeaderMenu/MenuDesktop.tsx
- front/src/components/Layout.tsx
- front/src/hooks/useErrorHandling.ts
- front/src/hooks/useNotification.ts
- front/src/views/Distributions/CreateDistributionSpotView/CreateDistributionSpotView.tsx
- front/src/views/Distributions/DistroEventView/components/State1Planning/DistroEventDetailsForPlanningStateContainer.tsx
- front/src/views/Distributions/DistroEventView/components/State2Packing/DistroEventDetailsForPackingState.tsx
- front/src/views/Distributions/DistroEventView/components/State2Packing/DistroEventDetailsForPackingStateContainer.tsx
- front/src/views/Distributions/DistroEventView/components/State2Packing/components/PackingAddBoxOrItemsForPackingListEntryOverlay/PackingScanBoxOrFindByLabelOverlayContent.tsx
> Fix desktop menu position and layout

- back/boxtribute_server/cli/main.py
- show organisation name
- skip confirmation in dry-run mode
> Enhance base-removal script

- front/src/views/Transfers/ShipmentsOverview/ShipmentsOverviewView.tsx
@aerinsol this fixes both the count and the recent bug for Manage Shipments.
> Fix Manage Shipments count and date bug

- front/src/views/Transfers/ShipmentView/ShipmentView.tsx
Overlooked in 71fcfb4495ac983c10c2b6edcbdaffc198c5638d (#1776 )
> Add missing fragment to SEND_SHIPMENT mutation

- front/src/views/Transfers/ShipmentsOverview/ShipmentsOverview.test.tsx
- front/src/views/Transfers/ShipmentsOverview/ShipmentsOverviewView.tsx
> Match manage shipments count calculation to transfer agreements

- front/src/components/HeaderMenu/MenuDesktop.tsx
- front/src/views/Box/components/BoxTabs.tsx
- front/src/views/Transfers/ShipmentsOverview/ShipmentsOverviewView.tsx
> Standarize tabs styling + uppercase section headers in sidebar

- front/src/components/HeaderMenu/MenuDesktop.tsx
> Fix sidebar bottom cut off due screen size and scaling

- front/src/hooks/useUnassignBoxesFromShipments.ts
- front/src/mocks/products.ts
- front/src/views/Boxes/BoxesView.test.tsx
- front/src/views/Boxes/components/ExportToCsvButton.tsx
FYI @HaGuesto @jlin95 @fhenrich33
> Show warning toast when trying to export without selected boxes

- front/src/views/Transfers/CreateTransferAgreement/components/CreateTransferAgreement.tsx
Replicating look of CreateShipment view:
> Add Nevermind button to CreateTransferAgreement form

- back/boxtribute_server/cli/main.py
- back/boxtribute_server/cli/remove_base_access.py
- back/boxtribute_server/cli/service.py
- back/test/model_tests/test_cli.py
- Soft-delete organisation if last active base deleted
- Print initial information about potentially removing organisation
> Soft-delete organisation when removing last active base

- front/src/views/Boxes/components/AssignTagsButton.tsx
Happened in the meantime in e41a9ff2, breaking build-front CI job on
master
> Fix chakra-react-select props in AssignTagsButton

- front/package.json
This reverts commit efc7400c8ea2dbbf72e9d2de7f8917f8fb26a559.
> Revert "Temporarily avoid errors with globalPreferences type in FE tests (#2011)"

- front/src/components/Layout.tsx
- front/src/views/Boxes/components/BoxesTable.tsx
- front/src/views/Products/components/ProductsTable.tsx
- front/src/views/Transfers/ShipmentView/ShipmentView.test.tsx
> Table and layout overflow css, only table content should scroll

- front/src/views/Boxes/components/TableCells.tsx
> Wrap popover trigger in a Box to avoid ref warning

- front/src/components/BoxReconciliationOverlay/components/BoxReconciliationAccordion.tsx
- front/src/components/BoxReconciliationOverlay/components/MatchProductsForm.tsx
- front/src/stores/globalCacheStore.ts
> Cached products take precedence over matched products

- front/package.json
- package.json
- pnpm-lock.yaml
Reverts boxwise/boxtribute#2115
> Revert "build(deps-dev): bump the front-dev-minor-update group across 2 directories with 4 updates"

- shared-components/statviz/components/ShareableLinkAlert.tsx
- shared-components/statviz/hooks/useShareableLink.ts
> Fix Share Link info/warning text and behavior

- statviz/src/App.tsx
> Fix tag filtering in public Statviz

- back/README.md
- back/boxtribute_server/authz.py
- docs/adr/adr_authorization-specification.md
@aerinsol please LMK if the beta-levels are clearer now. I'm a bit reluctant to introduce a Google Sheet because I don't want to end in the same situation as with permissions (source of truth not being clear; code and sheet diverging)
> Update README and comments about beta-level

- docs/assort/v1_20240523-products.md
https://github.com/boxwise/boxtribute/blob/update-assort-table-doc/docs/assort/v1_20240523-products.md
> update assort table doc

- back/boxtribute_server/business_logic/warehouse/product/crud.py
- back/test/endpoint_tests/test_product.py
- Change logic to find already enabled standard product instantiation
- Re-use previous instantiation when enabling standard product
- Set created_* instead of last_modified_* fields in re-enabled instantiation
> Update back-end when re-enabling standard-product

- front/src/App.tsx
- front/src/views/BoxCreate/BoxCreateView.tsx
- front/src/views/Boxes/components/BoxesActionsAndTable.tsx
Mobile viewport:
Mobile viewport BEFORE this PR:
> Create-box from ManageBoxes

- front/src/hooks/hooks.ts
- front/src/views/BoxCreate/BoxCreateView.tsx
- Make IUseTableConfigProps.defaultTableConfig optional
- Refetch BOXES_FOR_BOXESVIEW_QUERY after creating box
> refetch boxes for boxesview after create box

- front/src/views/Boxes/components/Checkbox.tsx
> Increase manage boxes table checkbox sizes

- front/src/App.tsx
- front/src/components/Form/SelectField.tsx
- front/src/queries/queries.ts
- front/src/queries/types.ts
- front/src/views/EditCustomProduct/EditCustomProductView.tsx
- front/src/views/EditCustomProduct/components/EditCustomProductForm.tsx
- front/src/views/EditStandardProduct/EditStandardProductView.tsx
- front/src/views/EditStandardProduct/components/EditStandardProductForm.tsx
- front/src/views/EnableStandardProduct/EnableStandardProductView.tsx
- front/src/views/EnableStandardProduct/components/transformer.ts
- front/src/views/Products/components/ProductsContainer.tsx
- front/src/views/Products/components/ProductsTable.tsx
- front/src/views/Products/components/transformers.ts
> Edit product standard instantiation

- front/src/views/Boxes/components/BoxesTable.tsx
> Show total count for boxes and items in manage boxes table header

- front/src/hooks/useAssignTags.ts
- front/src/hooks/useUnassignTags.ts
- front/src/queries/dynamic-mutations.ts
- front/src/views/Boxes/BoxesViewActions.test.tsx
- front/src/views/Boxes/components/AssignTagsButton.tsx
- front/src/views/Boxes/components/RemoveTagsButton.tsx
- front/src/views/QrReader/QrReaderMultiBoxAssignTags.test.tsx
compete with https://github.com/boxwise/boxtribute/pull/2233
> Use assignTagsToBoxes bulk mutation

- front/src/views/EnableStandardProduct/EnableStandardProductView.tsx
Similar to #2264
https://trello.com/c/UBmvCNiG
> Fix newly enabled standard product not showing up in product selection

- back/boxtribute_server/business_logic/box_transfer/agreement/crud.py
- back/test/endpoint_tests/test_transfer_agreement.py
> Prevent creating identical agreement
